Repository ut-issl/s2e-core, pull requests merged in 2022-05, with the labels that each got.

#124 Fix EXP component for tutorial
  src/Component/Abstract/EXP.cpp
  src/Component/Abstract/EXP.h
Labels: priority::high

#126 Fix NRLMSISE-00 CMake to use git
  ExtLibraries/nrlmsise00/CMakeLists.txt
Labels: priority::high, tools

#125 Fix docker setups
  scripts/Common/download_nrlmsise00_src_and_table.sh
  scripts/Docker_Ubuntu/Dockerfile
  scripts/Docker_Ubuntu/setup_docker.sh
Labels: documentation, tools

#128 Add Release style
  README.md
Labels: documentation, enhancement

#132 Update major version to 5
  CMakeLists.txt
Labels: priority::high

#136 Fix HILS build error
  common.cmake
Labels: bug, priority::high

#141 Initialize inertia tensor in controlled attitude
  src/Dynamics/Attitude/ControlledAttitude.cpp
  src/Dynamics/Attitude/ControlledAttitude.h
  src/Dynamics/Attitude/InitAttitude.cpp
Labels: bug, priority::high

#140 Add 64bit build option for linux
  .github/workflows/build.yml
  CMakeLists.txt
  ExtLibraries/CMakeLists.txt
  ExtLibraries/cspice/CMakeLists.txt
  ExtLibraries/cspice/install_step.cmake
  ExtLibraries/nrlmsise00/CMakeLists.txt
  common.cmake
Labels: priority::medium, tools

#144 Merge main into develop for bug fix
  src/Dynamics/Attitude/ControlledAttitude.cpp
  src/Dynamics/Attitude/ControlledAttitude.h
  src/Dynamics/Attitude/InitAttitude.cpp
Labels: priority::high
