Repository ut-issl/s2e-core, pull requests merged in 2022-04, with the labels that each got.

#73 Reduce cspice build
  .github/workflows/build.yml
  ExtLibraries/cspice/CMakeLists.txt
Labels: enhancement, tools

#76 Modify physical constants management
  src/Component/AOCS/GNSSReceiver.cpp
  src/Component/AOCS/GNSSReceiver.h
  src/Component/AOCS/STT.cpp
  src/Component/CommGS/GScalculator.cpp
  src/Component/CommGS/GScalculator.h
  src/Disturbance/AirDrag.cpp
  src/Disturbance/AirDrag.h
  src/Disturbance/GGDist.cpp
  src/Disturbance/GeoPotential.cpp
  src/Dynamics/Orbit/EarthCenteredOrbit.cpp
  src/Dynamics/Orbit/Orbit.h
  src/Dynamics/Orbit/SimpleCircularOrbit.cpp
  src/Dynamics/Thermal/Node.cpp
  src/Environment/Global/CelestialRotation.cpp
  src/Environment/Global/GnssSatellites.cpp
  src/Environment/Global/GnssSatellites.h
  src/Environment/Global/PhysicalConstants.hpp
  src/Environment/Local/SRPEnvironment.cpp
  src/Environment/Local/SRPEnvironment.h
  src/Library/igrf/igrf.cpp
  src/Library/math/Constant.hpp
  src/Library/nrlmsise00/Wrapper_nrlmsise00.cpp
  src/Simulation/GroundStation/GroundStation.cpp
  src/Simulation/GroundStation/GroundStation.h
Labels: priority::high

#78 Fix log output bug
  src/Simulation/SimulationConfig.h
Labels: bug, priority::high

#72 dump all clang-format config to .clang-format
  .clang-format
  .github/workflows/check-format.yml
Labels: tools

#79 Add Kepler and Encke orbit propagation method
  CMakeLists.txt
  data/SampleSat/ini/SampleSat.ini
  src/Dynamics/CMakeLists.txt
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.h
  src/Dynamics/Orbit/KeplerOrbitPropagation.cpp
  src/Dynamics/Orbit/KeplerOrbitPropagation.h
  src/Dynamics/Orbit/Orbit.h
  src/Interface/InitInput/Init_Orbit.cpp
  src/Library/Orbit/CMakeLists.txt
  src/Library/Orbit/KeplerOrbit.cpp
  src/Library/Orbit/KeplerOrbit.h
  src/Library/Orbit/OrbitalElements.cpp
  src/Library/Orbit/OrbitalElements.h
  src/Library/math/CMakeLists.txt
  src/Library/math/s2e_math.cpp
  src/Library/math/s2e_math.hpp
Labels: priority::medium

#84 Integrate frame conversion(ECI-ECEF-GEODETIC)
  CMakeLists.txt
  data/SampleSat/ini/SampleSat.ini
  src/Component/CommGS/GScalculator.cpp
  src/Component/CommGS/GScalculator.h
  src/Disturbance/GeoPotential.cpp
  src/Dynamics/CMakeLists.txt
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.h
  src/Dynamics/Orbit/KeplerOrbitPropagation.cpp
  src/Dynamics/Orbit/KeplerOrbitPropagation.h
  src/Dynamics/Orbit/Orbit.cpp
  src/Dynamics/Orbit/Orbit.h
  src/Dynamics/Orbit/RelativeOrbit.cpp
  src/Dynamics/Orbit/RelativeOrbit.h
  src/Dynamics/Orbit/Rk4OrbitPropagation.cpp
  src/Dynamics/Orbit/Rk4OrbitPropagation.h
  src/Dynamics/Orbit/Sgp4OrbitPropagation.cpp
  src/Dynamics/Orbit/Sgp4OrbitPropagation.h
  src/Environment/Global/CelestialRotation.h
  src/Environment/Global/PhysicalConstants.hpp
  src/Interface/InitInput/Init_Orbit.cpp
  src/Library/Geodesy/CMakeLists.txt
  src/Library/Geodesy/GeodeticPosition.cpp
  src/Library/Geodesy/GeodeticPosition.hpp
  src/Simulation/GroundStation/GroundStation.cpp
  src/Simulation/GroundStation/GroundStation.h
  src/Simulation/GroundStation/SampleGroundStation/SampleGS.cpp
  src/Simulation/GroundStation/SampleGroundStation/SampleGS.h
Labels: priority::medium

#92 Fix warnings in Vector-Matrix library
  src/Library/math/MatVec_impl.hpp
  src/Library/math/Matrix_tfs.hpp
  src/Library/math/Vector_tfs.hpp
Labels: priority::high

#93 Fix warnings with small modification
  src/Component/AOCS/GNSSReceiver.cpp
  src/Component/AOCS/RWJitter.cpp
  src/Component/AOCS/RWModel.cpp
  src/Component/AOCS/STT.cpp
  src/Component/AOCS/SunSensor.cpp
  src/Component/Abstract/ObcCommunicationBase.cpp
  src/Component/Abstract/ObcI2cTargetCommunicationBase.cpp
  src/Component/Logic/RVDController.cpp
  src/Component/Logic/UWBEstimator.cpp
  src/Component/Mission/Telescope/Telescope.cpp
  src/Component/Mission/Telescope/Telescope.h
  src/Component/Power/BAT.cpp
  src/Component/Power/PCU.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Environment/Global/CelestialInformation.cpp
  src/Environment/Local/LocalCelestialInformation.cpp
  src/Environment/Local/LocalEnvironment.cpp
  src/Environment/Local/MagEnvironment.cpp
  src/Interface/InitInput/IniAccess.h
  src/Interface/InitInput/IniAccessUnix.cpp
  src/Interface/InitInput/Init_CelesInfo.cpp
  src/Interface/LogOutput/LogUtility.h
  src/Interface/SpacecraftInOut/Ports/I2CPort.cpp
  src/Interface/SpacecraftInOut/Ports/I2CPort.h
  src/Library/Orbit/OrbitalElements.cpp
  src/Library/math/GlobalRand.cpp
  src/Library/nrlmsise00/Wrapper_nrlmsise00.cpp
  src/Library/utils/endian.cpp
  src/RelativeInformation/RelativeInformation.cpp
  src/Simulation/MCSim/InitParameter.h
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
Labels: priority::high

#95 実行時エラーを修正するための緊急のPR
  src/Library/math/MatVec_impl.hpp
Labels: priority::high

#86 Fix controlled attitude
  src/Dynamics/Attitude/ControlledAttitude.cpp
Labels: priority::high

#88 Add base class for installed components to fix acceleration log bug
  src/Simulation/CMakeLists.txt
  src/Simulation/Spacecraft/InstalledComponents.cpp
  src/Simulation/Spacecraft/InstalledComponents.hpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
  src/Simulation/Spacecraft/SampleSpacecraft/SampleSat.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleSat.h
  src/Simulation/Spacecraft/Spacecraft.cpp
  src/Simulation/Spacecraft/Spacecraft.h
Labels: priority::high

#96 Delete warning: destructors
  src/Component/CommGS/GScalculator.h
  src/Dynamics/Dynamics.h
  src/Dynamics/Thermal/Temperature.h
  src/Environment/Global/CelestialInformation.h
  src/Environment/Global/HipparcosCatalogue.h
  src/Environment/Global/SimTime.h
  src/Environment/Local/Atmosphere.h
  src/Environment/Local/LocalCelestialInformation.h
  src/Environment/Local/MagEnvironment.h
  src/Environment/Local/SRPEnvironment.h
  src/Simulation/Spacecraft/InstalledComponents.hpp
Labels: priority::high

#99 Add -Wextra to common compile option
  common.cmake
Labels: enhancement, tools

#101 delete const function return
  src/Component/AOCS/RWModel.h
  src/Component/AOCS/STT.h
  src/Component/AOCS/SunSensor.h
  src/Component/Abstract/ObcCommunicationBase.h
  src/Environment/Global/SimTime.h
  src/Interface/SpacecraftInOut/Ports/PowerPort.h
  src/Library/Orbit/OrbitalElements.h
  src/Library/optics/GaussianBeamBase.h
  src/Simulation/Spacecraft/Spacecraft.h
Labels: priority::high

#104 Show tools version step on build CI
  .github/workflows/build.yml
Labels: priority::low, tools

#109 Remove using namespace libra from headers
  src/Component/AOCS/EMDS.h
  src/Component/AOCS/RWModule.h
  src/Component/Logic/RVDController.h
Labels: priority::high

#107 Fix thermal initialization to avoid CSV file reading
  src/Dynamics/Thermal/InitTemperature.cpp
  src/Dynamics/Thermal/Temperature.cpp
  src/Dynamics/Thermal/Temperature.h
Labels: priority::high

#105 Fix unused param warnings
  src/Component/AOCS/GNSSReceiver.cpp
  src/Component/AOCS/Gyro.cpp
  src/Component/AOCS/MagSensor.cpp
  src/Component/AOCS/MagTorquer.cpp
  src/Component/AOCS/RWModel.cpp
  src/Component/AOCS/STT.cpp
  src/Component/AOCS/SunSensor.cpp
  src/Component/AOCS/rw_ode.cpp
  src/Component/Abstract/ComponentBase.h
  src/Component/Abstract/EXP.cpp
  src/Component/Abstract/ExpHils.cpp
  src/Component/Abstract/ExpHilsI2cController.cpp
  src/Component/Abstract/ExpHilsI2cTarget.cpp
  src/Component/Abstract/ObcI2cTargetCommunicationBase.cpp
  src/Component/CDH/OBC.cpp
  src/Component/CDH/OBC_C2A.cpp
  src/Component/CommGS/ANT.cpp
  src/Component/Logic/RVDController.cpp
  src/Component/Logic/RVDController.h
  src/Component/Mission/Telescope/Telescope.cpp
  src/Component/Power/BAT.cpp
  src/Component/Power/BAT.h
  src/Component/Power/PCU.cpp
  src/Component/Propulsion/SimpleThruster.cpp
  src/Component/Propulsion/SimpleThruster.h
  src/Disturbance/MagDisturbance.cpp
  src/Disturbance/SolarRadiation.cpp
  src/Disturbance/SolarRadiation.h
  src/Dynamics/Attitude/AttitudeRK4.cpp
  src/Dynamics/Attitude/ControlledAttitude.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.h
  src/Dynamics/Orbit/InitOrbit.cpp
  src/Dynamics/Orbit/KeplerOrbitPropagation.cpp
  src/Dynamics/Orbit/RelativeOrbit.cpp
  src/Dynamics/Orbit/RelativeOrbit.h
  src/Dynamics/Orbit/Rk4OrbitPropagation.cpp
  src/Dynamics/Orbit/Rk4OrbitPropagation.h
  src/Dynamics/Orbit/Sgp4OrbitPropagation.cpp
  src/Dynamics/Thermal/Temperature.cpp
  src/Environment/Global/GnssSatellites.cpp
  src/Interface/HilsInOut/HilsPortManager.cpp
  src/Interface/InitInput/IniAccess.cpp
  src/Interface/SpacecraftInOut/Ports/I2CPort.cpp
  src/Library/Orbit/KeplerOrbit.cpp
  src/Library/Orbit/KeplerOrbit.h
  src/Library/math/Quantization.cpp
  src/Library/math/RandomWalk_tfs.hpp
  src/Library/sgp4/sgp4unit.cpp
  src/Library/utils/Macros.hpp
  src/Simulation/GroundStation/GroundStation.cpp
  src/Simulation/GroundStation/SampleGroundStation/SampleGS.cpp
  src/Simulation/GroundStation/SampleGroundStation/SampleGS.h
  src/Simulation/InterSatComm/InterSatComm.cpp
  src/Simulation/MCSim/InitParameter.cpp
  src/Simulation/MCSim/InitParameter.h
  src/Simulation/Spacecraft/InstalledComponents.cpp
Labels: priority::high

#108 Refactor Attitude Dynamics
  data/SampleSat/ini/SampleSat.ini
  src/Dynamics/Attitude/Attitude.cpp
  src/Dynamics/Attitude/Attitude.h
  src/Dynamics/Attitude/AttitudeRK4.cpp
  src/Dynamics/Attitude/AttitudeRK4.h
  src/Dynamics/Attitude/ControlledAttitude.cpp
  src/Dynamics/Attitude/ControlledAttitude.h
  src/Dynamics/Attitude/InitAttitude.cpp
  src/Dynamics/CMakeLists.txt
Labels: priority::medium

#116 Fix const auto
  src/Component/Power/CsvScenarioInterface.cpp
Labels: priority::high

#114 Add clang build CI
  .github/workflows/build.yml
Labels: priority::low, tools

#118 Fix unknown pragma warnings
  src/Library/igrf/igrf.cpp
  src/Library/sgp4/sgp4ext.cpp
  src/Library/sgp4/sgp4io.cpp
  src/Library/sgp4/sgp4unit.cpp
Labels: priority::high

#119 Add Wpendatic warning option
  common.cmake
  src/Component/AOCS/InitGnssReceiver.cpp
  src/Component/AOCS/rw_ode.cpp
  src/Disturbance/AirDrag.cpp
  src/Environment/Global/CelestialRotation.cpp
  src/Environment/Global/PhysicalConstants.hpp
  src/Library/math/Constant.hpp
  src/Library/math/Matrix_ifs.hpp
  src/Library/nrlmsise00/Wrapper_nrlmsise00.cpp
  src/Simulation/Spacecraft/InstalledComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
Labels: priority::high
