Repository ut-issl/s2e-core, pull requests merged in 2022-03, with the labels that each got.

#31 Add an interface for HILS testing of I2C components
  src/Component/Abstract/ExpHilsI2cController.cpp
  src/Component/Abstract/ExpHilsI2cController.h
  src/Component/Abstract/ExpHilsI2cTarget.cpp
  src/Component/Abstract/ExpHilsI2cTarget.h
  src/Component/Abstract/I2cControllerCommunicationBase.cpp
  src/Component/Abstract/I2cControllerCommunicationBase.h
  src/Component/Abstract/ObcCommunicationBase.cpp
  src/Component/Abstract/ObcI2cCommunicationBase.cpp
  src/Component/Abstract/ObcI2cCommunicationBase.h
  src/Component/Abstract/ObcI2cTargetCommunicationBase.cpp
  src/Component/Abstract/ObcI2cTargetCommunicationBase.h
  src/Component/CMakeLists.txt
  src/Interface/HilsInOut/CMakeLists.txt
  src/Interface/HilsInOut/HilsPortManager.cpp
  src/Interface/HilsInOut/HilsPortManager.h
  src/Interface/HilsInOut/Ports/HilsI2cTargetPort.cpp
  src/Interface/HilsInOut/Ports/HilsI2cTargetPort.h
  src/Interface/HilsInOut/Ports/HilsUartPort.cpp
  src/Interface/HilsInOut/Ports/HilsUartPort.h
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
Labels: priority::low

#62 Add check clang-format workflow
  .github/workflows/check-format.yml
Labels: enhancement

#63 Remove I2C HILS example
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
Labels: bug
