Repository ut-issl/s2e-core, pull requests merged in 2022-01, with the labels that each got.

#11 Small modification of README
  README.md
Labels: priority::medium

#34 Fix labeler workflow
  .github/workflows/labeler.yml
Labels: priority::high, tools

#37 Add description of GitHub pages
  README.md
Labels: documentation, priority::high

#38 Reduce dependency to C2A
  CMakeLists.txt
  src/Component/CDH/OBC_C2A.cpp
Labels: priority::medium, C2A

#39 Build CI with GitHub Actions(windows runner)
  .github/workflows/build.yml
  ExtLibraries/CMakeLists.txt
  ExtLibraries/cspice/CMakeLists.txt
  ExtLibraries/cspice/install_step.cmake
  ExtLibraries/nrlmsise00/CMakeLists.txt
Labels: enhancement

#41 Add cache ExtLibraries in build CI
  .github/workflows/build.yml
Labels: enhancement

#43 Add Linux build CI
  .github/workflows/build.yml
  ExtLibraries/CMakeLists.txt
  ExtLibraries/cspice/CMakeLists.txt
  ExtLibraries/cspice/install_step.cmake
  ExtLibraries/nrlmsise00/CMakeLists.txt
Labels: enhancement

#47 Add build CI with C2A
  .github/workflows/build.yml
Labels: enhancement, C2A

#48 Custom FlightSW/C2A directories
  .github/workflows/build.yml
  CMakeLists.txt
Labels: enhancement, C2A
