Repository ut-issl/s2e-core, pull requests merged in 2022-11, with the labels that each got.

#215 Add plot script for body frame information
  scripts/Plot/common.py
  scripts/Plot/plot_body_frame_info.py
Labels: priority::medium, tools

#184 Add plot GS visivility on PR
  .github/workflows/build.yml
Labels: priority::low, tools, automation::comment-graph

#217 Fix bug in celestial information
  data/SampleSat/ini/SampleSimBase.ini
  src/Environment/Global/CelestialInformation.cpp
  src/Environment/Global/CelestialInformation.h
  src/Environment/Global/InitGlobalEnvironment.cpp
Labels: bug, priority::high

#230 hotfix: Fix bug in GNSS satellite latitude calculation
  src/Component/AOCS/GNSSReceiver.cpp
Labels: bug

#219 Merge main for hotfix #217
  data/SampleSat/ini/SampleSimBase.ini
  src/Environment/Global/CelestialInformation.cpp
  src/Environment/Global/CelestialInformation.h
  src/Environment/Global/InitGlobalEnvironment.cpp
Labels: bug, priority::high

#220 Add plot spacecraft orbit in ECI frame
  scripts/Plot/plot_orbit_eci.py
Labels: tools

#234 Fix workflow error
  .github/workflows/build.yml
  src/Environment/Global/CelestialInformation.cpp
Labels: bug, priority::high, tools

#233 Merge main for hotfix #230
  src/Component/AOCS/GNSSReceiver.cpp
Labels: bug, priority::high

#242 Add labels for versioning
  .github/labels.yml
Labels: documentation

#239 Add animation for orbit visualization
  scripts/Plot/plot_orbit_eci.py
Labels: gui

#244 Copy `ForceGenerator` from `s2e-ff`
  data/SampleSat/ini/SampleSat.ini
  data/SampleSat/ini/component/ForceGenerator.ini
  src/Component/CMakeLists.txt
  src/Component/IdealComponents/ForceGenerator.cpp
  src/Component/IdealComponents/ForceGenerator.hpp
  src/Component/IdealComponents/InitializeForceGenerator.cpp
  src/Component/IdealComponents/InitializeForceGenerator.hpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
Labels: priority::medium, component

#246 Update version in CMake to v5.1.0
  CMakeLists.txt
Labels: priority::high, minor update

#249 Add GetStructure method to Spacecraft class
  src/Simulation/Spacecraft/Spacecraft.h
Labels: enhancement, priority::low

#251 Copy sensor base initialization from s2e-ff
  src/Component/Abstract/InitializeSensorBase.hpp
  src/Component/Abstract/InitializeSensorBase_tfs.hpp
Labels: priority::medium, component, minor update

#253 Read `ini` file in plot to get ground station position
  scripts/Plot/plot_gs_visibility.py
  src/Simulation/GroundStation/GroundStation.cpp
Labels: priority::medium, gui, minor update
