Repository ut-issl/s2e-core, pull requests merged in 2022-07, with the labels that each got.

#148 Rename from minimum_user_for_s2e to minimum_user
  .github/workflows/build.yml
Labels: icebox, priority::medium, C2A

#155 Fix set -rdynamic on link time only
  common.cmake
Labels: priority::low, tools

#157 TelescopeへのGetterの追加
  src/Component/Mission/Telescope/Telescope.h
Labels: priority::high

#163 Fix ini comment position(it breaks cspice)
  data/SampleSat/ini/SampleSimBase.ini
Labels: priority::high

#129 Run sample simulation on CI
  .github/labels.yml
  .github/workflows/build.yml
  data/SampleSat/gen_graph.sh
  data/SampleSat/graph.toml
Labels: tools

#153 Add plot scripts
  .gitignore
  scripts/Plot/make_miller_projection_map.py
  scripts/Plot/plot_gs_visibility.py
  scripts/Plot/plot_satellite_orbit_on_miller.py
  scripts/Plot/requirements.txt
Labels: priority::medium, tools

#161 Modify for FF simulation
  src/RelativeInformation/RelativeInformation.cpp
  src/RelativeInformation/RelativeInformation.h
Labels: priority::medium

#170 Move to Pipfile for python tools package definition from requirements.txt
  .github/workflows/validate-scripts.yml
  scripts/Plot/Pipfile
  scripts/Plot/Pipfile.lock
  scripts/Plot/requirements.txt
Labels: tools

#172 Update require Python version to 3.8 in scripts
  .github/workflows/validate-scripts.yml
  scripts/Plot/Pipfile
  scripts/Plot/Pipfile.lock
Labels: tools

#171 Use argparse in plot scripts
  scripts/Plot/plot_gs_visibility.py
  scripts/Plot/plot_satellite_orbit_on_miller.py
Labels: tools

#180 [hotfix] Fix initial orbit to avoid zero inclination
  data/SampleSat/ini/SampleSat.ini
Labels: bug, priority::high

#179 [hotfix] Fix acceleration logging bug for RK4 and ENCKE
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Dynamics/Orbit/Rk4OrbitPropagation.cpp
Labels: bug, priority::high

#176 Add function driven when the component power off
  src/Component/AOCS/MagTorquer.cpp
  src/Component/AOCS/MagTorquer.h
  src/Component/AOCS/RWModel.cpp
  src/Component/AOCS/RWModel.h
  src/Component/Abstract/ComponentBase.cpp
  src/Component/Abstract/ComponentBase.h
  src/Component/Propulsion/SimpleThruster.cpp
  src/Component/Propulsion/SimpleThruster.h
Labels: priority::high

#181 Merge main into develop for bug fix
  data/SampleSat/ini/SampleSat.ini
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Dynamics/Orbit/Rk4OrbitPropagation.cpp
Labels: priority::high

#173 Improve validate-scripts CI
  .github/workflows/validate-scripts.yml
Labels: tools

#174 Plot latest log
  scripts/Plot/common.py
  scripts/Plot/plot_gs_visibility.py
  scripts/Plot/plot_satellite_orbit_on_miller.py
Labels: tools

#182 Plot with no gui
  scripts/Plot/.gitignore
  scripts/Plot/plot_gs_visibility.py
  scripts/Plot/plot_satellite_orbit_on_miller.py
Labels: enhancement, tools

#185 Fix singularity when i=0
  src/Library/Orbit/OrbitalElements.cpp
Labels: priority::high

#186 Merge main into develop for bug fix in OrbitalElements
  src/Library/Orbit/OrbitalElements.cpp
Labels: bug, priority::high

#187 Fix version in CMakeLists.txt
  CMakeLists.txt
Labels: priority::high, tools
