Repository ut-issl/s2e-core, pull requests merged in 2022-12, with the labels that each got.

#259 Fix comments in `RelativeInformation`
  src/RelativeInformation/RelativeInformation.cpp
  src/RelativeInformation/RelativeInformation.h
Labels: documentation, priority::high, minor update

#256 Fix comments in `Simulation`
  src/S2E.cpp
  src/S2E_parallel.cpp
  src/Simulation/Case/SampleCase.cpp
  src/Simulation/Case/SampleCase.h
  src/Simulation/Case/SimulationCase.cpp
  src/Simulation/Case/SimulationCase.h
  src/Simulation/GroundStation/GroundStation.cpp
  src/Simulation/GroundStation/GroundStation.h
  src/Simulation/GroundStation/SampleGroundStation/SampleGS.cpp
  src/Simulation/GroundStation/SampleGroundStation/SampleGS.h
  src/Simulation/GroundStation/SampleGroundStation/SampleGSComponents.cpp
  src/Simulation/GroundStation/SampleGroundStation/SampleGSComponents.h
  src/Simulation/InterSatComm/InterSatComm.cpp
  src/Simulation/InterSatComm/InterSatComm.h
  src/Simulation/MCSim/InitMcSim.cpp
  src/Simulation/MCSim/InitMcSim.hpp
  src/Simulation/MCSim/InitParameter.cpp
  src/Simulation/MCSim/InitParameter.h
  src/Simulation/MCSim/MCSimExecutor.cpp
  src/Simulation/MCSim/MCSimExecutor.h
  src/Simulation/MCSim/SimulationObject.cpp
  src/Simulation/MCSim/SimulationObject.h
  src/Simulation/SimulationConfig.h
  src/Simulation/Spacecraft/InstalledComponents.cpp
  src/Simulation/Spacecraft/InstalledComponents.hpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
  src/Simulation/Spacecraft/SampleSpacecraft/SampleSat.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleSat.h
  src/Simulation/Spacecraft/SampleSpacecraft/Sample_PortConfig.h
  src/Simulation/Spacecraft/Spacecraft.cpp
  src/Simulation/Spacecraft/Spacecraft.h
  src/Simulation/Spacecraft/Structure/InitStructure.cpp
  src/Simulation/Spacecraft/Structure/InitStructure.hpp
  src/Simulation/Spacecraft/Structure/KinematicsParams.cpp
  src/Simulation/Spacecraft/Structure/KinematicsParams.h
  src/Simulation/Spacecraft/Structure/RMMParams.cpp
  src/Simulation/Spacecraft/Structure/RMMParams.h
  src/Simulation/Spacecraft/Structure/Structure.cpp
  src/Simulation/Spacecraft/Structure/Structure.h
  src/Simulation/Spacecraft/Structure/Surface.cpp
  src/Simulation/Spacecraft/Structure/Surface.h
Labels: documentation, priority::high, simulation, minor update

#260 Fix comment in `Disturbance`
  src/Disturbance/AccelerationDisturbance.h
  src/Disturbance/AirDrag.cpp
  src/Disturbance/AirDrag.h
  src/Disturbance/Disturbance.h
  src/Disturbance/Disturbances.cpp
  src/Disturbance/Disturbances.h
  src/Disturbance/GeoPotential.cpp
  src/Disturbance/GeoPotential.h
  src/Disturbance/GravityGradient.cpp
  src/Disturbance/GravityGradient.hpp
  src/Disturbance/InitDisturbance.cpp
  src/Disturbance/InitDisturbance.hpp
  src/Disturbance/MagDisturbance.cpp
  src/Disturbance/MagDisturbance.h
  src/Disturbance/SimpleDisturbance.h
  src/Disturbance/SolarRadiation.cpp
  src/Disturbance/SolarRadiation.h
  src/Disturbance/SurfaceForce.cpp
  src/Disturbance/SurfaceForce.h
  src/Disturbance/ThirdBodyGravity.cpp
  src/Disturbance/ThirdBodyGravity.h
Labels: documentation, priority::high, disturbance, minor update

#265 Fix comment interface
  src/Interface/HilsInOut/COSMOSWrapper.cpp
  src/Interface/HilsInOut/COSMOSWrapper.h
  src/Interface/HilsInOut/COSMOS_TCP_IF.cpp
  src/Interface/HilsInOut/COSMOS_TCP_IF.h
  src/Interface/HilsInOut/ComPortInterface.cpp
  src/Interface/HilsInOut/ComPortInterface.h
  src/Interface/HilsInOut/HardwareMessage.cpp
  src/Interface/HilsInOut/HardwareMessage.h
  src/Interface/HilsInOut/HilsPortManager.cpp
  src/Interface/HilsInOut/HilsPortManager.h
  src/Interface/HilsInOut/InitCosmosWrapper.cpp
  src/Interface/HilsInOut/InitHardwareMessage.cpp
  src/Interface/HilsInOut/Ports/HilsI2cTargetPort.cpp
  src/Interface/HilsInOut/Ports/HilsI2cTargetPort.h
  src/Interface/HilsInOut/Ports/HilsUartPort.cpp
  src/Interface/HilsInOut/Ports/HilsUartPort.h
  src/Interface/InitInput/IniAccess.cpp
  src/Interface/InitInput/IniAccess.h
  src/Interface/LogOutput/ILoggable.h
  src/Interface/LogOutput/InitLog.cpp
  src/Interface/LogOutput/InitLog.hpp
  src/Interface/LogOutput/LogUtility.h
  src/Interface/LogOutput/Logger.cpp
  src/Interface/LogOutput/Logger.h
  src/Interface/SpacecraftInOut/Ports/GPIOPort.cpp
  src/Interface/SpacecraftInOut/Ports/GPIOPort.h
  src/Interface/SpacecraftInOut/Ports/I2CPort.cpp
  src/Interface/SpacecraftInOut/Ports/I2CPort.h
  src/Interface/SpacecraftInOut/Ports/PowerPort.cpp
  src/Interface/SpacecraftInOut/Ports/PowerPort.h
  src/Interface/SpacecraftInOut/Ports/SCIPort.cpp
  src/Interface/SpacecraftInOut/Ports/SCIPort.h
  src/Interface/SpacecraftInOut/TMTCDriver.cpp
  src/Interface/SpacecraftInOut/TMTCDriver.h
  src/Interface/SpacecraftInOut/Utils/ITCTMChannel.h
  src/Interface/SpacecraftInOut/Utils/RingBuffer.cpp
  src/Interface/SpacecraftInOut/Utils/RingBuffer.h
Labels: documentation, priority::medium, minor update

#271 Fix comments in Environment
  src/Environment/Global/CelestialInformation.cpp
  src/Environment/Global/CelestialInformation.h
  src/Environment/Global/CelestialRotation.cpp
  src/Environment/Global/CelestialRotation.h
  src/Environment/Global/ClockGenerator.cpp
  src/Environment/Global/ClockGenerator.h
  src/Environment/Global/GlobalEnvironment.cpp
  src/Environment/Global/GlobalEnvironment.h
  src/Environment/Global/GnssSatellites.cpp
  src/Environment/Global/GnssSatellites.h
  src/Environment/Global/HipparcosCatalogue.cpp
  src/Environment/Global/HipparcosCatalogue.h
  src/Environment/Global/InitGlobalEnvironment.cpp
  src/Environment/Global/InitGlobalEnvironment.hpp
  src/Environment/Global/InitGnssSatellites.cpp
  src/Environment/Global/InitGnssSatellites.hpp
  src/Environment/Global/PhysicalConstants.hpp
  src/Environment/Global/SimTime.cpp
  src/Environment/Global/SimTime.h
  src/Environment/Local/Atmosphere.cpp
  src/Environment/Local/Atmosphere.h
  src/Environment/Local/InitLocalEnvironment.cpp
  src/Environment/Local/InitLocalEnvironment.hpp
  src/Environment/Local/LocalCelestialInformation.cpp
  src/Environment/Local/LocalCelestialInformation.h
  src/Environment/Local/LocalEnvironment.cpp
  src/Environment/Local/LocalEnvironment.h
  src/Environment/Local/MagEnvironment.cpp
  src/Environment/Local/MagEnvironment.h
  src/Environment/Local/SRPEnvironment.cpp
  src/Environment/Local/SRPEnvironment.h
Labels: priority::medium, environment, minor update

#272 Fix comments in dynamics
  src/Dynamics/Attitude/Attitude.cpp
  src/Dynamics/Attitude/Attitude.h
  src/Dynamics/Attitude/AttitudeRK4.cpp
  src/Dynamics/Attitude/AttitudeRK4.h
  src/Dynamics/Attitude/ControlledAttitude.cpp
  src/Dynamics/Attitude/ControlledAttitude.h
  src/Dynamics/Attitude/InitAttitude.cpp
  src/Dynamics/Attitude/InitAttitude.hpp
  src/Dynamics/Dynamics.cpp
  src/Dynamics/Dynamics.h
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.h
  src/Dynamics/Orbit/InitOrbit.cpp
  src/Dynamics/Orbit/InitOrbit.hpp
  src/Dynamics/Orbit/KeplerOrbitPropagation.cpp
  src/Dynamics/Orbit/KeplerOrbitPropagation.h
  src/Dynamics/Orbit/Orbit.cpp
  src/Dynamics/Orbit/Orbit.h
  src/Dynamics/Orbit/RelativeOrbit.cpp
  src/Dynamics/Orbit/RelativeOrbit.h
  src/Dynamics/Orbit/Rk4OrbitPropagation.cpp
  src/Dynamics/Orbit/Rk4OrbitPropagation.h
  src/Dynamics/Orbit/Sgp4OrbitPropagation.cpp
  src/Dynamics/Orbit/Sgp4OrbitPropagation.h
Labels: priority::medium, dynamics, minor update

#280 Fix unit comment
  src/Environment/Global/CelestialInformation.h
Labels: documentation, priority::low

#273 Fix comments in library
  src/Library/Geodesy/GeodeticPosition.cpp
  src/Library/Geodesy/GeodeticPosition.hpp
  src/Library/Orbit/KeplerOrbit.cpp
  src/Library/Orbit/KeplerOrbit.h
  src/Library/Orbit/OrbitalElements.cpp
  src/Library/Orbit/OrbitalElements.h
  src/Library/RelativeOrbit/RelativeOrbitModels.cpp
  src/Library/RelativeOrbit/RelativeOrbitModels.h
  src/Library/igrf/igrf.h
  src/Library/math/GlobalRand.cpp
  src/Library/math/GlobalRand.h
  src/Library/math/MatVec.hpp
  src/Library/math/MatVec_impl.hpp
  src/Library/math/Matrix.hpp
  src/Library/math/Matrix_ifs.hpp
  src/Library/math/Matrix_tfs.hpp
  src/Library/math/NormalRand.cpp
  src/Library/math/NormalRand.hpp
  src/Library/math/NormalRand_ifs.hpp
  src/Library/math/ODE.hpp
  src/Library/math/ODE_ifs.hpp
  src/Library/math/ODE_impl.hpp
  src/Library/math/ODE_tfs.hpp
  src/Library/math/Quantization.cpp
  src/Library/math/Quantization.h
  src/Library/math/Quaternion.cpp
  src/Library/math/Quaternion.hpp
  src/Library/math/Quaternion_ifs.hpp
  src/Library/math/Ran0.cpp
  src/Library/math/Ran0.hpp
  src/Library/math/Ran1.cpp
  src/Library/math/Ran1.hpp
  src/Library/math/RandomWalk.hpp
  src/Library/math/RandomWalk_tfs.hpp
  src/Library/math/TestQuaternion.cpp
  src/Library/math/Vector.cpp
  src/Library/math/Vector.hpp
  src/Library/math/Vector_ifs.hpp
  src/Library/math/Vector_tfs.hpp
  src/Library/math/s2e_math.cpp
  src/Library/math/s2e_math.hpp
  src/Library/nrlmsise00/Wrapper_nrlmsise00.cpp
  src/Library/nrlmsise00/Wrapper_nrlmsise00.h
  src/Library/optics/GaussianBeamBase.cpp
  src/Library/optics/GaussianBeamBase.h
  src/Library/utils/ENDIAN_DEFINE.h
  src/Library/utils/Macros.hpp
  src/Library/utils/endian.cpp
  src/Library/utils/endian.h
  src/Library/utils/slip.cpp
  src/Library/utils/slip.h
Labels: priority::medium, library, minor update

#285 Add initialize mode for orbit
  data/SampleSat/ini/SampleSat.ini
  src/Dynamics/Orbit/InitOrbit.cpp
  src/Dynamics/Orbit/InitOrbit.hpp
  src/Dynamics/Orbit/Orbit.cpp
  src/Dynamics/Orbit/Orbit.h
  src/Dynamics/Orbit/RelativeOrbit.cpp
  src/Dynamics/Orbit/Rk4OrbitPropagation.cpp
  src/Dynamics/Orbit/Sgp4OrbitPropagation.cpp
Labels: priority::high, dynamics, minor update

#284 Add antenna radiation pattern read from CSV file
  data/SampleSat/ini/SampleSat.ini
  data/SampleSat/ini/component/ANT.ini
  data/SampleSat/ini/component/ANT_GS.ini
  data/SampleSat/ini/component/ANT_SC.ini
  data/SampleSat/ini/component/AntennaRadiationPatternCsv/SampleAntennaRadiationPattern.csv
  src/Component/CMakeLists.txt
  src/Component/CommGS/Antenna.cpp
  src/Component/CommGS/Antenna.hpp
  src/Component/CommGS/AntennaRadiationPattern.cpp
  src/Component/CommGS/AntennaRadiationPattern.hpp
  src/Component/CommGS/InitAntenna.cpp
  src/Component/CommGS/InitAntenna.hpp
  src/Interface/InitInput/IniAccess.h
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
Labels: priority::high, component, minor update

#286 Revert "Set DOWNLOAD_EXTRACT_TIMESTAMP option to ExternalProject_Add()"
  ExtLibraries/cspice/CMakeLists.txt
Labels: tools, library, minor update

#287 Fix CMake minimum required version in ExtLibraries by FetchContent DOWNLOAD_NO_EXTRACT
  ExtLibraries/CMakeLists.txt
  ExtLibraries/cspice/CMakeLists.txt
  ExtLibraries/nrlmsise00/CMakeLists.txt
Labels: bug, tools

#288 Update v5.2.0
  CMakeLists.txt
Labels: priority::high, minor update
