Repository ut-issl/s2e-core, pull requests merged in 2023-08, with the labels that each got.

#466 Add geopotential partial derivative
  CMakeLists.txt
  src/library/gravity/gravity_potential.cpp
  src/library/gravity/gravity_potential.hpp
  src/library/gravity/test_gravity_potential.cpp
Labels: priority::medium, disturbance, minor update

#464 Add lunar gravity field disturbance
  ExtLibraries/CMakeLists.txt
  ExtLibraries/lunar_gravity_field/CMakeLists.txt
  data/sample/initialize_files/sample_disturbance.ini
  src/disturbances/CMakeLists.txt
  src/disturbances/disturbances.cpp
  src/disturbances/initialize_disturbances.cpp
  src/disturbances/initialize_disturbances.hpp
  src/disturbances/lunar_gravity_field.cpp
  src/disturbances/lunar_gravity_field.hpp
Labels: priority::medium, disturbance, minor update

#469 Update v6.3.0
  CMakeLists.txt
Labels: priority::high, minor update

#468 Fix UTC time tag log output
  src/environment/global/simulation_time.cpp
Labels: priority::high, gui, patch

#472 Support c2a-core v4 (rename System directory)
  src/components/real/cdh/on_board_computer_with_c2a.cpp
Labels: priority::high, tools, C2A

#474 Update v6.4.0
  CMakeLists.txt
Labels: priority::high, minor update

#475 Main merge for minor update v6.4.0
  CMakeLists.txt
  scripts/Plot/Pipfile.lock
  src/components/real/cdh/on_board_computer_with_c2a.cpp
Labels: priority::high, minor update

#478 Remove initialize file for global environment
  src/environment/global/CMakeLists.txt
  src/environment/global/celestial_information.cpp
  src/environment/global/celestial_information.hpp
  src/environment/global/global_environment.cpp
  src/environment/global/global_environment.hpp
  src/environment/global/hipparcos_catalogue.cpp
  src/environment/global/hipparcos_catalogue.hpp
  src/environment/global/initialize_global_environment.cpp
  src/environment/global/initialize_global_environment.hpp
  src/environment/global/simulation_time.cpp
  src/environment/global/simulation_time.hpp
  src/library/initialize/initialize_file_access.hpp
Labels: priority::medium, environment, minor update
