Repository ut-issl/s2e-core, pull requests merged in 2023-10, with the labels that each got.

#500 Remove override warning
  src/simulation_sample/spacecraft/sample_components.hpp
Labels: priority::medium, patch

#494 Fix for RW initial rotation
  src/components/real/aocs/reaction_wheel.cpp
Labels: priority::medium, component, patch

#501 Modify celestial rotation to suit coding rule
  src/environment/global/celestial_rotation.cpp
  src/environment/global/celestial_rotation.hpp
Labels: priority::medium, environment, patch

#504 Fix required python version for python-utils
  scripts/Plot/Pipfile.lock
Labels: priority::high, tools, automation::comment-graph, gui, patch

#499 Add new functions for ini read as `std::vector`
  src/library/initialize/initialize_file_access.cpp
  src/library/initialize/initialize_file_access.hpp
Labels: priority::medium, library, minor update

#495 Fix ephemeris time handling to improve calculation speed
  src/environment/global/celestial_information.cpp
  src/environment/global/celestial_information.hpp
  src/environment/global/global_environment.cpp
  src/environment/global/simulation_time.cpp
  src/environment/global/simulation_time.hpp
Labels: priority::medium, environment, patch

#487 Add DP5 propagator
  src/library/numerical_integration/dormand_prince_5.hpp
  src/library/numerical_integration/dormand_prince_5_implementation.hpp
  src/library/numerical_integration/numerical_integrator_manager.hpp
  src/library/numerical_integration/runge_kutta_4.hpp
  src/library/numerical_integration/runge_kutta_fehlberg_implementation.hpp
  src/library/numerical_integration/test_runge_kutta.cpp
Labels: priority::medium, library, minor update

#505 Remove warnings
  CMakeLists.txt
  src/components/real/communication/antenna.cpp
  src/components/real/power/battery.cpp
  src/components/real/power/pcu_initial_study.cpp
  src/components/real/power/solar_array_panel.cpp
  src/dynamics/thermal/heater.cpp
  src/dynamics/thermal/heater.hpp
  src/environment/global/gnss_satellites.cpp
Labels: priority::medium, patch

#485 Add C2A command sender for accelerated SILS test
  data/sample/initialize_files/components/wings_command_sender_to_c2a/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  data/sample/initialize_files/components/wings_command_sender_to_c2a/example.ops
  data/sample/initialize_files/components/wings_command_sender_to_c2a/wings_command_sender_to_c2a.ini
  src/components/CMakeLists.txt
  src/components/real/cdh/on_board_computer_with_c2a.cpp
  src/components/real/communication/wings_command_sender_to_c2a.cpp
  src/components/real/communication/wings_command_sender_to_c2a.hpp
  src/library/CMakeLists.txt
  src/library/initialize/c2a_command_database.cpp
  src/library/initialize/c2a_command_database.hpp
  src/library/initialize/wings_operation_file.cpp
  src/library/initialize/wings_operation_file.hpp
Labels: priority::medium, C2A, WINGS, component, minor update

#506 Fix C2A Command sender
  data/sample/initialize_files/components/wings_command_sender_to_c2a/example.ops
  src/library/initialize/c2a_command_database.cpp
Labels: bug, priority::high, patch

#508 Fix typos
  data/sample/initialize_files/sample_gnss.ini
  data/sample/initialize_files/sample_satellite.ini
  src/components/examples/example_serial_communication_for_hils.hpp
  src/components/examples/example_serial_communication_with_obc.cpp
  src/components/real/cdh/on_board_computer_with_c2a.hpp
  src/components/real/mission/telescope.cpp
  src/components/real/propulsion/simple_thruster.cpp
  src/environment/global/initialize_gnss_satellites.cpp
  src/simulation_sample/spacecraft/sample_components.cpp
Labels: priority::medium, patch

#507 Remove initialize files in thermal
  src/dynamics/CMakeLists.txt
  src/dynamics/dynamics.hpp
  src/dynamics/thermal/heater.cpp
  src/dynamics/thermal/heater.hpp
  src/dynamics/thermal/heater_controller.cpp
  src/dynamics/thermal/heater_controller.hpp
  src/dynamics/thermal/heatload.cpp
  src/dynamics/thermal/heatload.hpp
  src/dynamics/thermal/initialize_heater.cpp
  src/dynamics/thermal/initialize_heater.hpp
  src/dynamics/thermal/initialize_heatload.cpp
  src/dynamics/thermal/initialize_heatload.hpp
  src/dynamics/thermal/initialize_node.cpp
  src/dynamics/thermal/initialize_node.hpp
  src/dynamics/thermal/initialize_temperature.cpp
  src/dynamics/thermal/initialize_temperature.hpp
  src/dynamics/thermal/node.cpp
  src/dynamics/thermal/node.hpp
  src/dynamics/thermal/temperature.cpp
  src/dynamics/thermal/temperature.hpp
Labels: priority::medium, dynamics, major update

#511 Add moon rotation
  data/sample/initialize_files/sample_simulation_base.ini
  src/disturbances/lunar_gravity_field.cpp
  src/environment/global/CMakeLists.txt
  src/environment/global/celestial_information.cpp
  src/environment/global/celestial_information.hpp
  src/environment/global/earth_rotation.cpp
  src/environment/global/moon_rotation.cpp
  src/environment/global/moon_rotation.hpp
  src/library/CMakeLists.txt
  src/library/initialize/initialize_file_access.cpp
  src/library/initialize/initialize_file_access.hpp
  src/library/planet_rotation/moon_rotation_utilities.cpp
  src/library/planet_rotation/moon_rotation_utilities.hpp
Labels: priority::medium, environment, minor update

#513 Information update for v7.0.0
  CMakeLists.txt
  README.md
Labels: documentation, priority::medium, patch

#515 Add comment for Moon rotation correction value
  src/library/planet_rotation/moon_rotation_utilities.cpp
Labels: priority::medium, patch

#514 Modify for multi-sensors and multi-MTQs interference
  data/sample/initialize_files/components/component_interference.ini
  src/components/real/aocs/mtq_magnetometer_interference.cpp
  src/components/real/aocs/mtq_magnetometer_interference.hpp
Labels: priority::medium, component, patch

#518 Modify component_intererenece.ini file
  data/sample/initialize_files/components/component_interference.ini
Labels: priority::low, patch

#519 Fix include c2a-core v4
  src/components/real/cdh/on_board_computer_with_c2a.cpp
  src/components/real/communication/wings_command_sender_to_c2a.cpp
Labels: bug, priority::high, C2A, component, patch

#521 Merge develop to main for hotfix #519
  src/components/real/cdh/on_board_computer_with_c2a.cpp
  src/components/real/communication/wings_command_sender_to_c2a.cpp
Labels: priority::high, patch

#522 Merge main to develop for Hotfix #468
  src/environment/global/simulation_time.cpp
Labels: priority::high, patch

#523 Refactor GNSS satellites class
  data/sample/initialize_files/sample_gnss.ini
  src/components/real/aocs/gnss_receiver.cpp
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/environment/global/initialize_gnss_satellites.cpp
Labels: priority::medium, environment, patch

#526 Add interpolation library
  CMakeLists.txt
  src/library/CMakeLists.txt
  src/library/gnss/sp3_file_reader.hpp
  src/library/initialize/c2a_command_database.hpp
  src/library/math/interpolation.cpp
  src/library/math/interpolation.hpp
  src/library/math/test_interpolation.cpp
Labels: priority::medium, library, minor update

#527 Modify build target file list for Google Test
  CMakeLists.txt
Labels: priority::medium, tools, patch

#528 Remove sscanf warnings in VS build
  src/library/gnss/sp3_file_reader.cpp
  src/library/time_system/date_time_format.hpp
Labels: priority::medium, patch

#530 Add GNSS satellite nubmer library
  src/library/CMakeLists.txt
  src/library/gnss/gnss_satellite_number.cpp
  src/library/gnss/gnss_satellite_number.hpp
  src/library/gnss/test_gnss_satellite_number.cpp
Labels: priority::medium, library, minor update

#531 Add GNSS satellite log output
  scripts/Plot/plot_gnss_satellites.py
  src/environment/global/global_environment.cpp
  src/environment/global/gnss_satellites.cpp
Labels: priority::medium, gui, environment, minor update

#533 Fix loss of data warning
  src/environment/global/gnss_satellites.cpp
Labels: priority::medium, patch

#532 Add third body shadow
  data/sample/initialize_files/sample_local_environment.ini
  src/environment/local/solar_radiation_pressure_environment.cpp
  src/environment/local/solar_radiation_pressure_environment.hpp
Labels: priority::medium, environment, minor update
