Repository ut-issl/s2e-core, pull requests merged in 2023-03, with the labels that each got.

#342 Fix CSV output log header
  src/environment/local/atmosphere.cpp
Labels: priority::medium, gui, major update

#339 Fix enum naming rule
  src/components/base/i2c_controller.cpp
  src/components/base/i2c_controller.hpp
  src/components/base/i2c_target_communication_with_obc.cpp
  src/components/base/i2c_target_communication_with_obc.hpp
  src/components/base/uart_communication_with_obc.cpp
  src/components/base/uart_communication_with_obc.hpp
  src/components/real/aocs/gnss_receiver.cpp
  src/components/real/aocs/gnss_receiver.hpp
  src/components/real/aocs/gyro_sensor.cpp
  src/components/real/aocs/initialize_gnss_receiver.cpp
  src/components/real/communication/antenna.cpp
  src/components/real/communication/antenna.hpp
  src/components/real/communication/initialize_antenna.cpp
  src/dynamics/attitude/controlled_attitude.cpp
  src/dynamics/attitude/controlled_attitude.hpp
  src/dynamics/orbit/relative_orbit.cpp
  src/dynamics/orbit/relative_orbit.hpp
  src/environment/global/celestial_rotation.cpp
  src/environment/global/celestial_rotation.hpp
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/environment/global/initialize_global_environment.cpp
  src/environment/global/initialize_gnss_satellites.cpp
  src/library/orbit/relative_orbit_models.hpp
  src/simulation/monte_carlo_simulation/initialize_monte_carlo_parameters.cpp
  src/simulation/monte_carlo_simulation/initialize_monte_carlo_parameters.hpp
  src/simulation/monte_carlo_simulation/initialize_monte_carlo_simulation.cpp
  src/simulation/spacecraft/sample_spacecraft/sample_port_configuration.hpp
Labels: priority::medium, major update

#340 Add test for math library
  CMakeLists.txt
  src/library/math/test_matrix.cpp
  src/library/math/test_matrix_vector.cpp
  src/library/math/test_quaternion.cpp
  src/library/math/test_s2e_math.cpp
  src/library/math/test_vector.cpp
Labels: test, minor update

#359 Rename `GeoPotential`
  src/disturbances/disturbances.cpp
  src/disturbances/geopotential.cpp
  src/disturbances/geopotential.hpp
  src/disturbances/gravity_gradient.hpp
  src/disturbances/initialize_disturbances.cpp
  src/disturbances/initialize_disturbances.hpp
Labels: priority::medium, disturbance, major update

#357 Move to member function in Matrix class
  src/disturbances/geopotential.cpp
  src/dynamics/attitude/controlled_attitude.cpp
  src/environment/global/celestial_rotation.cpp
  src/library/math/matrix.hpp
  src/library/math/matrix_template_functions.hpp
  src/library/math/test_matrix.cpp
  src/simulation/ground_station/ground_station.cpp
Labels: priority::medium, library, major update

#360 Modify disturbance base
  src/disturbances/acceleration_disturbance.hpp
  src/disturbances/disturbance.hpp
  src/disturbances/disturbances.cpp
  src/disturbances/disturbances.hpp
  src/disturbances/geopotential.cpp
  src/disturbances/geopotential.hpp
  src/disturbances/gravity_gradient.cpp
  src/disturbances/gravity_gradient.hpp
  src/disturbances/magnetic_disturbance.cpp
  src/disturbances/magnetic_disturbance.hpp
  src/disturbances/simple_disturbance.hpp
  src/disturbances/surface_force.cpp
  src/disturbances/surface_force.hpp
  src/disturbances/third_body_gravity.cpp
  src/disturbances/third_body_gravity.hpp
Labels: disturbance

#341 Add plot for environment calculation
  scripts/Plot/plot_air_density.py
  scripts/Plot/plot_celestial_orbit_i.py
  scripts/Plot/plot_geomagnetic_field.py
  scripts/Plot/plot_solar_radiation_environment.py
Labels: priority::medium, gui, environment, minor update

#343 Add plot for gyro sensor
  scripts/Plot/plot_gyro_sensor.py
Labels: priority::medium, gui, component, minor update

#344 Fix gyro sensor default noise
  data/sample/initialize_files/components/gyro_sensor.ini
Labels: priority::medium, gui, component, patch

#346 Add plot for magnetometer
  scripts/Plot/plot_magnetometer.py
Labels: priority::medium, gui, component, minor update

#347 Add plot star sensor
  scripts/Plot/Pipfile
  scripts/Plot/Pipfile.lock
  scripts/Plot/common.py
  scripts/Plot/plot_star_sensor.py
Labels: priority::medium, gui, component, minor update

#348 Add plot sun sensor
  scripts/Plot/plot_sun_sensor
Labels: priority::medium, gui, component, minor update

#349 Add plot for gnss receiver
  scripts/Plot/plot_gnss_receiver.py
Labels: priority::medium, gui, component, minor update

#350 Add plot for magnetorquer
  scripts/Plot/plot_magnetorquer.py
Labels: priority::medium, gui, component, minor update

#351 Add plot for RW
  scripts/Plot/plot_reaction_wheel.py
Labels: priority::medium, gui, component, minor update

#352 Add plot for simple thruster
  scripts/Plot/plot_simple_thruster.py
Labels: priority::medium, gui, component, minor update

#353 Add plot force generator
  scripts/Plot/plot_force_generator.py
Labels: priority::medium, gui, component, minor update

#354 Add plot for torque generator
  scripts/Plot/plot_torque_generator.py
Labels: priority::medium, gui, component, minor update

#355 Add plot for Ground Station Calculator
  scripts/Plot/plot_ground_station_calculator.py
Labels: priority::medium, gui, component, minor update

#361 Move `gen_graph`
  .github/workflows/build.yml
  scripts/Plot/gen_graph.sh
  scripts/Plot/graph.toml
Labels: priority::medium, tools, gui, major update

#362 Fix header file extension
  src/library/utilities/endian.cpp
  src/library/utilities/endian.hpp
  src/library/utilities/slip.cpp
  src/library/utilities/slip.hpp
Labels: priority::medium, library, major update

#363 Fix include guard Macro name
  src/components/base/gpio_connection_with_obc.hpp
  src/library/communication/com_port_interface.hpp
Labels: priority::medium, patch

#364 Update link margin analysis
  data/sample/initialize_files/components/ground_station_antenna.ini
  data/sample/initialize_files/components/spacecraft_antenna.ini
  src/components/real/communication/antenna.cpp
  src/components/real/communication/antenna.hpp
  src/components/real/communication/ground_station_calculator.cpp
  src/components/real/communication/initialize_antenna.cpp
  src/simulation/ground_station/ground_station.cpp
Labels: priority::medium, component, major update

#367 Fix Visual Studio warnings
  src/components/examples/example_serial_communication_with_obc.cpp
  src/components/examples/example_serial_communication_with_obc.hpp
  src/components/real/cdh/on_board_computer.hpp
  src/components/real/mission/telescope.cpp
  src/components/real/mission/telescope.hpp
  src/dynamics/orbit/encke_orbit_propagation.cpp
  src/dynamics/orbit/kepler_orbit_propagation.cpp
  src/dynamics/orbit/kepler_orbit_propagation.hpp
  src/dynamics/orbit/relative_orbit.cpp
  src/dynamics/orbit/relative_orbit.hpp
  src/dynamics/orbit/rk4_orbit_propagation.cpp
  src/dynamics/orbit/rk4_orbit_propagation.hpp
  src/dynamics/orbit/sgp4_orbit_propagation.cpp
  src/environment/global/celestial_information.cpp
  src/environment/local/local_celestial_information.cpp
Labels: priority::high, patch

#369 Small fix for simulation
  src/simulation/case/sample_case.cpp
  src/simulation/case/sample_case.hpp
  src/simulation/ground_station/ground_station.hpp
  src/simulation/ground_station/sample_ground_station/sample_ground_station.hpp
Labels: priority::high, simulation, patch

#370 Fix ini file description
  data/sample/initialize_files/sample_local_environment.ini
  src/environment/local/initialize_local_environment.cpp
Labels: priority::high, gui, environment, major update

#371 Refactor `Simulation` directory to simplify for users
  src/environment/global/global_environment.cpp
  src/environment/global/global_environment.hpp
  src/simulation/case/sample_case.cpp
  src/simulation/case/sample_case.hpp
  src/simulation/case/simulation_case.cpp
  src/simulation/case/simulation_case.hpp
  src/simulation/ground_station/ground_station.hpp
  src/simulation/multiple_spacecraft/relative_information.hpp
  src/simulation/spacecraft/spacecraft.cpp
  src/simulation/spacecraft/spacecraft.hpp
Labels: priority::high, simulation, major update

#372 Make `simulation_sample` directory
  CMakeLists.txt
  src/s2e.cpp
  src/simulation_sample/case/sample_case.cpp
  src/simulation_sample/case/sample_case.hpp
  src/simulation_sample/ground_station/sample_ground_station.cpp
  src/simulation_sample/ground_station/sample_ground_station.hpp
  src/simulation_sample/ground_station/sample_ground_station_components.cpp
  src/simulation_sample/ground_station/sample_ground_station_components.hpp
  src/simulation_sample/spacecraft/sample_components.cpp
  src/simulation_sample/spacecraft/sample_components.hpp
  src/simulation_sample/spacecraft/sample_port_configuration.hpp
  src/simulation_sample/spacecraft/sample_spacecraft.cpp
  src/simulation_sample/spacecraft/sample_spacecraft.hpp
Labels: priority::high, simulation, major update

#373 Fix include path in telescope.hpp
  src/components/real/mission/telescope.hpp
Labels: priority::high, component, patch
