Repository ut-issl/s2e-core, pull requests merged in 2023-02, with the labels that each got.

#302 Delete unmanaged codes
  data/SampleSat/ini/component/EMDS.ini
  data/SampleSat/ini/component/UWBSensor.ini
  src/Component/AOCS/EMDS.cpp
  src/Component/AOCS/EMDS.h
  src/Component/AOCS/InitEmds.cpp
  src/Component/AOCS/InitEmds.hpp
  src/Component/AOCS/InitUwbSensor.cpp
  src/Component/AOCS/InitUwbSensor.hpp
  src/Component/AOCS/RWModule.cpp
  src/Component/AOCS/RWModule.h
  src/Component/AOCS/UWBSensor.cpp
  src/Component/AOCS/UWBSensor.h
  src/Component/Abstract/Singleton.h
  src/Component/Abstract/StateMachine.h
  src/Component/CDH/TMTCInterface.cpp
  src/Component/CDH/TMTCInterface.h
  src/Component/CMakeLists.txt
  src/Component/Logic/LPF.cpp
  src/Component/Logic/LPF.h
  src/Component/Logic/PIDController.h
  src/Component/Logic/RVDController.cpp
  src/Component/Logic/RVDController.h
  src/Component/Logic/UWBEstimator.cpp
  src/Component/Logic/UWBEstimator.h
  src/Interface/HilsInOut/COSMOSWrapper.cpp
  src/Interface/HilsInOut/COSMOSWrapper.h
  src/Interface/HilsInOut/COSMOS_TCP_IF.cpp
  src/Interface/HilsInOut/COSMOS_TCP_IF.h
  src/Interface/SpacecraftInOut/CMakeLists.txt
  src/Interface/SpacecraftInOut/TMTCDriver.cpp
  src/Interface/SpacecraftInOut/TMTCDriver.h
  src/S2E_parallel.cpp
Labels: priority::medium, major update

#306 Add ideal torque generator
  data/SampleSat/ini/SampleSat.ini
  data/SampleSat/ini/component/TorqueGenerator.ini
  src/Component/CMakeLists.txt
  src/Component/IdealComponents/ForceGenerator.cpp
  src/Component/IdealComponents/ForceGenerator.hpp
  src/Component/IdealComponents/InitializeTorqueGenerator.cpp
  src/Component/IdealComponents/InitializeTorqueGenerator.hpp
  src/Component/IdealComponents/TorqueGenerator.cpp
  src/Component/IdealComponents/TorqueGenerator.hpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
Labels: priority::medium, component, minor update

#307 Move example components to `examples` directory
  src/Component/Abstract/EXP.cpp
  src/Component/CMakeLists.txt
  src/Component/examples/example_change_structure.cpp
  src/Component/examples/example_change_structure.hpp
  src/Component/examples/example_i2c_controller_for_hils.cpp
  src/Component/examples/example_i2c_controller_for_hils.hpp
  src/Component/examples/example_i2c_target_for_hils.cpp
  src/Component/examples/example_i2c_target_for_hils.hpp
  src/Component/examples/example_serial_communication_for_hils.cpp
  src/Component/examples/example_serial_communication_for_hils.hpp
  src/Component/examples/example_serial_communication_with_obc.cpp
  src/Component/examples/example_serial_communication_with_obc.hpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.cpp
  src/Simulation/Spacecraft/SampleSpacecraft/SampleComponents.h
Labels: component, major update

#305 Fix CSV output naming
  scripts/Plot/common.py
  scripts/Plot/plot_body_frame_info.py
  scripts/Plot/plot_disturbance_force.py
  scripts/Plot/plot_disturbance_torque.py
  scripts/Plot/plot_gs_visibility.py
  scripts/Plot/plot_orbit_eci.py
  scripts/Plot/plot_satellite_orbit_on_miller.py
  src/Component/AOCS/GNSSReceiver.cpp
  src/Component/AOCS/GNSSReceiver.h
  src/Component/AOCS/Gyro.cpp
  src/Component/AOCS/MagSensor.cpp
  src/Component/AOCS/MagTorquer.cpp
  src/Component/AOCS/RWModel.cpp
  src/Component/AOCS/STT.cpp
  src/Component/AOCS/SunSensor.cpp
  src/Component/CommGS/GScalculator.cpp
  src/Component/IdealComponents/ForceGenerator.cpp
  src/Component/IdealComponents/TorqueGenerator.cpp
  src/Component/Mission/Telescope/Telescope.cpp
  src/Component/Power/BAT.cpp
  src/Component/Power/PCU_InitialStudy.cpp
  src/Component/Power/SAP.cpp
  src/Component/Propulsion/SimpleThruster.cpp
  src/Disturbance/AirDrag.cpp
  src/Disturbance/GeoPotential.cpp
  src/Disturbance/GravityGradient.cpp
  src/Disturbance/MagDisturbance.cpp
  src/Disturbance/ThirdBodyGravity.cpp
  src/Dynamics/Attitude/Attitude.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.cpp
  src/Dynamics/Orbit/EnckeOrbitPropagation.h
  src/Dynamics/Orbit/KeplerOrbitPropagation.cpp
  src/Dynamics/Orbit/KeplerOrbitPropagation.h
  src/Dynamics/Orbit/Orbit.cpp
  src/Dynamics/Orbit/Orbit.h
  src/Dynamics/Orbit/RelativeOrbit.cpp
  src/Dynamics/Orbit/RelativeOrbit.h
  src/Dynamics/Orbit/Rk4OrbitPropagation.cpp
  src/Dynamics/Orbit/Rk4OrbitPropagation.h
  src/Dynamics/Orbit/Sgp4OrbitPropagation.cpp
  src/Dynamics/Orbit/Sgp4OrbitPropagation.h
  src/Environment/Global/CelestialInformation.cpp
  src/Environment/Global/SimTime.cpp
  src/Environment/Local/Atmosphere.cpp
  src/Environment/Local/LocalCelestialInformation.cpp
  src/Environment/Local/MagEnvironment.cpp
  src/Environment/Local/SRPEnvironment.cpp
  src/Interface/LogOutput/LogUtility.h
  src/Simulation/GroundStation/GroundStation.cpp
Labels: priority::medium, automation::comment-graph, gui, major update

#309 Add ID information for RW
  src/Component/AOCS/InitRwModel.cpp
  src/Component/AOCS/RWModel.cpp
  src/Component/AOCS/RWModel.h
Labels: priority::medium, gui, component, major update

#310 Add component ID
  data/sample/initialize_files/components/gnss_receiver.ini
  data/sample/initialize_files/components/gyro_sensor.ini
  data/sample/initialize_files/components/magnetometer.ini
  data/sample/initialize_files/components/magnetorquer.ini
  data/sample/initialize_files/components/pcu_initial_study.ini
  data/sample/initialize_files/components/star_sensor.ini
  src/Component/AOCS/InitGnssReceiver.cpp
  src/Component/AOCS/InitGyro.cpp
  src/Component/AOCS/InitMagSensor.cpp
  src/Component/AOCS/InitMagTorquer.cpp
  src/Component/AOCS/InitStt.cpp
Labels: gui, component, major update

#318 Integrate CMakeList for library and interface
  CMakeLists.txt
  src/interface/CMakeLists.txt
  src/interface/hils/CMakeLists.txt
  src/interface/initialize/CMakeLists.txt
  src/interface/log_output/CMakeLists.txt
  src/interface/sils/CMakeLists.txt
  src/library/CMakeLists.txt
  src/library/geodesy/CMakeLists.txt
  src/library/igrf/CMakeLists.txt
  src/library/inih/CMakeLists.txt
  src/library/math/CMakeLists.txt
  src/library/nrlmsise00/CMakeLists.txt
  src/library/optics/CMakeLists.txt
  src/library/orbit/CMakeLists.txt
  src/library/sgp4/CMakeLists.txt
  src/library/utilities/CMakeLists.txt
Labels: priority::medium, library, major update

#319 Fix file names in component/base_classes
  src/components/CMakeLists.txt
  src/components/aocs/gnss_receiver.hpp
  src/components/aocs/gyro_sensor.hpp
  src/components/aocs/initialize_gyro_sensor.cpp
  src/components/aocs/initialize_magnetometer.cpp
  src/components/aocs/magnetometer.hpp
  src/components/aocs/magnetorquer.hpp
  src/components/aocs/reaction_wheel.hpp
  src/components/aocs/star_sensor.hpp
  src/components/aocs/sun_sensor.hpp
  src/components/base/component.cpp
  src/components/base/component.hpp
  src/components/base/gpio_connection_with_obc.cpp
  src/components/base/gpio_connection_with_obc.hpp
  src/components/base/i2c_controller.cpp
  src/components/base/i2c_controller.hpp
  src/components/base/i2c_target_communication_with_obc.cpp
  src/components/base/i2c_target_communication_with_obc.hpp
  src/components/base/initialize_sensor.hpp
  src/components/base/initialize_sensor_template_functions.hpp
  src/components/base/interface_gpio_component.hpp
  src/components/base/interface_tickable.hpp
  src/components/base/sensor.hpp
  src/components/base/sensor_template_functions.hpp
  src/components/base/uart_communication_with_obc.cpp
  src/components/base/uart_communication_with_obc.hpp
  src/components/cdh/obc.hpp
  src/components/examples/example_change_structure.hpp
  src/components/examples/example_i2c_controller_for_hils.hpp
  src/components/examples/example_i2c_target_for_hils.hpp
  src/components/examples/example_serial_communication_for_hils.hpp
  src/components/examples/example_serial_communication_with_obc.hpp
  src/components/ideal_components/force_generator.hpp
  src/components/ideal_components/torque_generator.hpp
  src/components/mission/telescope.hpp
  src/components/power/battery.hpp
  src/components/power/pcu_initial_study.hpp
  src/components/power/power_control_unit.hpp
  src/components/power/solar_array_panel.hpp
  src/components/propulsion/simple_thruster.hpp
  src/environment/global/clock_generator.hpp
  src/interface/hils/com_port_interface.hpp
  src/interface/sils/ports/gpio_port.hpp
Labels: priority::medium, component, major update

#320 Add Newton method to solve Kepler equation
  src/Library/Orbit/KeplerOrbit.cpp
  src/Library/Orbit/KeplerOrbit.h
Labels: dynamics, minor update

#323 Add common function for log file path argument
  scripts/Plot/common.py
  scripts/Plot/plot_body_frame_info.py
  scripts/Plot/plot_disturbance_force.py
  scripts/Plot/plot_disturbance_torque.py
  scripts/Plot/plot_gs_visibility.py
  scripts/Plot/plot_orbit_eci.py
  scripts/Plot/plot_satellite_orbit_on_miller.py
Labels: automation::comment-graph, gui, major update

#325 Add spacecraft 3D model
  scripts/Plot/Pipfile
  scripts/Plot/Pipfile.lock
  scripts/Plot/common.py
  scripts/Plot/data/sample_6u_cubesat.stl
  scripts/Plot/plot_body_frame_info.py
Labels: gui

#322 Delete old CI
  .gitlab-ci.yml
  scripts/CI/build_on_vs2019.bat
Labels: major update

#327 Refactor disturbances
  data/sample/initialize_files/sample_disturbance.ini
  src/disturbances/acceleration_disturbance.hpp
  src/disturbances/air_drag.cpp
  src/disturbances/air_drag.hpp
  src/disturbances/disturbance.hpp
  src/disturbances/disturbances.cpp
  src/disturbances/disturbances.hpp
  src/disturbances/geopotential.cpp
  src/disturbances/geopotential.hpp
  src/disturbances/gravity_gradient.cpp
  src/disturbances/gravity_gradient.hpp
  src/disturbances/initialize_disturbances.cpp
  src/disturbances/initialize_disturbances.hpp
  src/disturbances/magnetic_disturbance.cpp
  src/disturbances/magnetic_disturbance.hpp
  src/disturbances/simple_disturbance.hpp
  src/disturbances/solar_radiation_pressure_disturbance.cpp
  src/disturbances/solar_radiation_pressure_disturbance.hpp
  src/disturbances/surface_force.cpp
  src/disturbances/surface_force.hpp
  src/disturbances/third_body_gravity.cpp
  src/disturbances/third_body_gravity.hpp
  src/simulation/spacecraft/spacecraft.cpp
Labels: priority::medium, disturbance, minor update

#332 Refactor dynamics
  src/components/ideal/force_generator.cpp
  src/components/real/aocs/gnss_receiver.cpp
  src/components/real/communication/ground_station_calculator.cpp
  src/disturbances/air_drag.cpp
  src/disturbances/geopotential.cpp
  src/disturbances/gravity_gradient.cpp
  src/disturbances/gravity_gradient.hpp
  src/disturbances/initialize_disturbances.cpp
  src/disturbances/initialize_disturbances.hpp
  src/disturbances/third_body_gravity.cpp
  src/dynamics/attitude/attitude.cpp
  src/dynamics/attitude/attitude.hpp
  src/dynamics/attitude/attitude_rk4.cpp
  src/dynamics/attitude/attitude_rk4.hpp
  src/dynamics/attitude/controlled_attitude.cpp
  src/dynamics/attitude/controlled_attitude.hpp
  src/dynamics/attitude/initialize_attitude.cpp
  src/dynamics/attitude/initialize_attitude.hpp
  src/dynamics/dynamics.cpp
  src/dynamics/dynamics.hpp
  src/dynamics/orbit/encke_orbit_propagation.cpp
  src/dynamics/orbit/encke_orbit_propagation.hpp
  src/dynamics/orbit/initialize_orbit.cpp
  src/dynamics/orbit/initialize_orbit.hpp
  src/dynamics/orbit/kepler_orbit_propagation.cpp
  src/dynamics/orbit/kepler_orbit_propagation.hpp
  src/dynamics/orbit/orbit.cpp
  src/dynamics/orbit/orbit.hpp
  src/dynamics/orbit/relative_orbit.cpp
  src/dynamics/orbit/relative_orbit.hpp
  src/dynamics/orbit/rk4_orbit_propagation.cpp
  src/dynamics/orbit/rk4_orbit_propagation.hpp
  src/dynamics/orbit/sgp4_orbit_propagation.cpp
  src/dynamics/orbit/sgp4_orbit_propagation.hpp
  src/dynamics/thermal/initialize_node.cpp
  src/dynamics/thermal/node.cpp
  src/dynamics/thermal/node.hpp
  src/dynamics/thermal/temperature.cpp
  src/dynamics/thermal/temperature.hpp
  src/environment/local/local_environment.cpp
  src/simulation/case/sample_case.cpp
  src/simulation/ground_station/ground_station.cpp
  src/simulation/multiple_spacecraft/relative_information.cpp
  src/simulation/spacecraft/spacecraft.cpp
Labels: dynamics, major update
