Repository ut-issl/s2e-core, pull requests merged in 2023-04, with the labels that each got.

#375 add attitude initialize mode
  data/sample/initialize_files/sample_satellite.ini
  src/dynamics/attitude/controlled_attitude.cpp
  src/dynamics/attitude/initialize_attitude.cpp
Labels: priority::high, dynamics, minor update

#378 Small fixes before final merge for v6.0.0
  data/sample/initialize_files/sample_simulation_base.ini
  data/sample/initialize_files/sample_structure.ini
  src/dynamics/attitude/attitude.cpp
  src/dynamics/attitude/attitude.hpp
  src/dynamics/attitude/attitude_rk4.cpp
  src/dynamics/attitude/attitude_rk4.hpp
  src/dynamics/attitude/controlled_attitude.hpp
  src/dynamics/attitude/initialize_attitude.cpp
  src/library/logger/initialize_log.cpp
Labels: priority::high, patch

#380 Modify log output feature for Monte Carlo simulation
  src/library/logger/logger.cpp
  src/library/logger/logger.hpp
  src/simulation/case/simulation_case.cpp
Labels: priority::high, gui, simulation, major update

#385 [HotFix] Add buffer initialize in UART communication
  src/components/base/uart_communication_with_obc.cpp
Labels: bug, priority::high, component, patch

#387 Update version info to v6.0.1
  CMakeLists.txt
Labels: documentation, priority::high, patch

#386 Merge main for hotfix #385
  CMakeLists.txt
  src/components/base/uart_communication_with_obc.cpp
Labels: bug, priority::high, component, patch

#388 [Hotfix] Fix log header for relative information
  CMakeLists.txt
  src/simulation/multiple_spacecraft/relative_information.cpp
Labels: priority::high, gui, patch

#389 Merge main to develop for #388
  CMakeLists.txt
  src/simulation/multiple_spacecraft/relative_information.cpp
Labels: priority::high, patch
