Repository ut-issl/s2e-core, pull requests merged in 2023-09, with the labels that each got.

#483 Fix interpolation algorithm for numerical integration
  src/library/numerical_integration/embedded_runge_kutta_implementation.hpp
  src/library/numerical_integration/numerical_integrator.hpp
  src/library/numerical_integration/runge_kutta_4.hpp
  src/library/numerical_integration/runge_kutta_fehlberg.hpp
  src/library/numerical_integration/runge_kutta_fehlberg_implementation.hpp
  src/library/numerical_integration/test_runge_kutta.cpp
Labels: priority::medium, minor update

#480 Add interference effect to Magnetometers from MTQs
  data/sample/initialize_files/components/component_interference.ini
  data/sample/initialize_files/sample_satellite.ini
  src/components/CMakeLists.txt
  src/components/base/sensor.hpp
  src/components/base/sensor_template_functions.hpp
  src/components/real/aocs/magnetometer.hpp
  src/components/real/aocs/magnetorquer.hpp
  src/components/real/aocs/mtq_magnetometer_interference.cpp
  src/components/real/aocs/mtq_magnetometer_interference.hpp
  src/simulation/spacecraft/installed_components.hpp
  src/simulation/spacecraft/spacecraft.cpp
  src/simulation_sample/spacecraft/sample_components.cpp
  src/simulation_sample/spacecraft/sample_components.hpp
Labels: priority::medium, component, minor update

#479 Remove initialize file for local environment
  src/environment/local/CMakeLists.txt
  src/environment/local/atmosphere.cpp
  src/environment/local/atmosphere.hpp
  src/environment/local/geomagnetic_field.cpp
  src/environment/local/geomagnetic_field.hpp
  src/environment/local/initialize_local_environment.cpp
  src/environment/local/initialize_local_environment.hpp
  src/environment/local/local_environment.cpp
  src/environment/local/solar_radiation_pressure_environment.cpp
  src/environment/local/solar_radiation_pressure_environment.hpp
  src/library/initialize/initialize_file_access.hpp
Labels: priority::medium, environment, minor update

#481 Remove initialize file for disturbance
  src/disturbances/CMakeLists.txt
  src/disturbances/air_drag.cpp
  src/disturbances/air_drag.hpp
  src/disturbances/disturbances.cpp
  src/disturbances/geopotential.cpp
  src/disturbances/geopotential.hpp
  src/disturbances/gravity_gradient.cpp
  src/disturbances/gravity_gradient.hpp
  src/disturbances/initialize_disturbances.cpp
  src/disturbances/initialize_disturbances.hpp
  src/disturbances/lunar_gravity_field.cpp
  src/disturbances/lunar_gravity_field.hpp
  src/disturbances/magnetic_disturbance.cpp
  src/disturbances/magnetic_disturbance.hpp
  src/disturbances/solar_radiation_pressure_disturbance.cpp
  src/disturbances/solar_radiation_pressure_disturbance.hpp
  src/disturbances/third_body_gravity.cpp
  src/disturbances/third_body_gravity.hpp
Labels: priority::medium, disturbance, minor update

#492 Feature/temporary modification for acceleration
  src/Environment/Global/CelestialInformation.cpp
  src/Environment/Global/CelestialInformation.h
  src/Environment/Global/GlobalEnvironment.cpp
  src/Environment/Global/SimTime.cpp
  src/Environment/Global/SimTime.h
Labels: priority::medium, patch

#471 Solve fixmes and todos in thermal simulation (Re-re-open, change base repository)
  src/dynamics/dynamics.cpp
  src/dynamics/thermal/heater.cpp
  src/dynamics/thermal/heater.hpp
  src/dynamics/thermal/heater_controller.cpp
  src/dynamics/thermal/heater_controller.hpp
  src/dynamics/thermal/heatload.cpp
  src/dynamics/thermal/heatload.hpp
  src/dynamics/thermal/initialize_heater.cpp
  src/dynamics/thermal/initialize_heatload.cpp
  src/dynamics/thermal/initialize_node.cpp
  src/dynamics/thermal/initialize_temperature.cpp
  src/dynamics/thermal/initialize_temperature.hpp
  src/dynamics/thermal/node.cpp
  src/dynamics/thermal/node.hpp
  src/dynamics/thermal/temperature.cpp
  src/dynamics/thermal/temperature.hpp
  src/environment/global/physical_constants.hpp
  src/environment/local/solar_radiation_pressure_environment.cpp
  src/environment/local/solar_radiation_pressure_environment.hpp
Labels: priority::medium, dynamics, minor update

#498 Update PR and issue templates
  .github/ISSUE_TEMPLATE/action_item.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, priority::medium, tools, patch

#488 Add Slope initialization in constructor for interpolation
  src/library/numerical_integration/dormand_prince_5_implementation.hpp
  src/library/numerical_integration/runge_kutta_4.hpp
  src/library/numerical_integration/runge_kutta_fehlberg_implementation.hpp
Labels: bug, priority::medium, patch
