Repository ut-issl/s2e-core, pull requests merged in 2023-05, with the labels that each got.

#399 [Hotfix] Fix typo magetometer
  CMakeLists.txt
  data/sample/initialize_files/sample_satellite.ini
  src/components/real/aocs/initialize_magnetometer.cpp
  src/components/real/aocs/initialize_magnetometer.hpp
  src/simulation_sample/spacecraft/sample_components.cpp
Labels: priority::high, component, patch

#402 Add zero check in endian function
  src/library/utilities/endian.cpp
Labels: priority::high, library, patch

#404 [Hotfix] Fix SS plot file name
  CMakeLists.txt
  scripts/Plot/plot_sun_sensor.py
Labels: priority::high, tools, gui, patch

#403 Fix inertia tensor handling in Attitude class
  src/components/examples/example_change_structure.cpp
  src/dynamics/attitude/attitude.cpp
  src/dynamics/attitude/attitude.hpp
  src/dynamics/attitude/attitude_rk4.cpp
  src/dynamics/attitude/attitude_rk4.hpp
  src/dynamics/attitude/controlled_attitude.cpp
  src/dynamics/attitude/initialize_attitude.cpp
  src/dynamics/attitude/initialize_attitude.hpp
Labels: priority::high, dynamics, minor update

#401 Merge main to develop for #399 and #404
  CMakeLists.txt
  data/sample/initialize_files/sample_satellite.ini
  scripts/Plot/plot_sun_sensor.py
  src/components/real/aocs/initialize_magnetometer.cpp
  src/components/real/aocs/initialize_magnetometer.hpp
  src/simulation_sample/spacecraft/sample_components.cpp
Labels: priority::high, patch

#406 Fix default SpaceWeather file name
  CMakeLists.txt
  data/sample/initialize_files/sample_local_environment.ini
Labels: priority::high, patch

#407 Merge main to develop for #406
  CMakeLists.txt
  data/sample/initialize_files/sample_local_environment.ini
Labels: priority::high, patch

#409 64bit build settings for VS
  .github/workflows/build.yml
  CMakeLists.txt
  CMakeSettings.json
  ExtLibraries/CMakeSettings.json
  ExtLibraries/cspice/CMakeLists.txt
Labels: priority::high, tools, minor update

#376 Add plot with Python for star position in telescope
  scripts/Plot/add_plot_telescope.py
Labels: priority::medium, tools, gui, minor update

#410 Add Python plot for the beta angle
  scripts/Plot/plot_beta_angle.py
Labels: priority::medium, tools, gui, minor update

#395 add thermal simulation
  data/sample/initialize_files/sample_satellite.ini
  data/sample/initialize_files/sample_simulation_base.ini
  data/sample/initialize_files/sample_thermal.ini
  data/sample/initialize_files/thermal_csv_files/cij.csv
  data/sample/initialize_files/thermal_csv_files/heaters.csv
  data/sample/initialize_files/thermal_csv_files/heatload.csv
  data/sample/initialize_files/thermal_csv_files/node.csv
  data/sample/initialize_files/thermal_csv_files/rij.csv
  data/sample/initialize_files/thermal_csv_files/temperture_sensors.csv
  data/sample/initialize_files/thermal_csv_files/thermal_components.csv
  src/dynamics/CMakeLists.txt
  src/dynamics/dynamics.cpp
  src/dynamics/thermal/heater.cpp
  src/dynamics/thermal/heater.hpp
  src/dynamics/thermal/heater_controller.cpp
  src/dynamics/thermal/heater_controller.hpp
  src/dynamics/thermal/heatload.cpp
  src/dynamics/thermal/heatload.hpp
  src/dynamics/thermal/initialize_heater.cpp
  src/dynamics/thermal/initialize_heater.hpp
  src/dynamics/thermal/initialize_heatload.cpp
  src/dynamics/thermal/initialize_heatload.hpp
  src/dynamics/thermal/initialize_node.cpp
  src/dynamics/thermal/initialize_node.hpp
  src/dynamics/thermal/initialize_temperature.cpp
  src/dynamics/thermal/initialize_temperature.hpp
  src/dynamics/thermal/node.cpp
  src/dynamics/thermal/node.hpp
  src/dynamics/thermal/temperature.cpp
  src/dynamics/thermal/temperature.hpp
  src/environment/global/physical_constants.hpp
  src/library/initialize/initialize_file_access.cpp
  src/library/initialize/initialize_file_access.hpp
Labels: priority::medium, dynamics, minor update

#412 Fix warnings in gcc build
  src/dynamics/thermal/node.cpp
Labels: priority::high, patch

#413 Fix bug in STT time delay
  src/components/real/aocs/star_sensor.cpp
Labels: bug, priority::high, component, patch

#416 fix plot_gs_visibility
  scripts/Plot/plot_gs_visibility.py
Labels: bug, priority::high, gui, patch

#419 Add python-utils
  .github/workflows/build.yml
  scripts/Plot/Pipfile
  scripts/Plot/Pipfile.lock
Labels: priority::high, gui, patch
