Repository ut-issl/s2e-core, pull requests merged in 2024-12, with the labels that each got.

#719 [Hotfix] Fix build error on WINGS command sender
  src/components/real/communication/wings_command_sender_to_c2a.hpp
Labels: bug, priority::high, patch

#721 Merge main into develop for hotfix #719
  src/components/real/communication/wings_command_sender_to_c2a.hpp
Labels: bug, priority::high, patch

#722 [Hotfix] Fix namespace bug
  src/components/real/communication/wings_command_sender_to_c2a.cpp
Labels: bug, priority::high, patch

#723 Merge main into develop for #722
  src/components/real/communication/wings_command_sender_to_c2a.cpp
Labels: bug, priority::high, patch

#724 Fix C2A interface
  src/components/real/cdh/c2a_communication.hpp
  src/components/real/cdh/on_board_computer_with_c2a.cpp
Labels: priority::high, C2A, patch

#725 Main merge to develop for v8.0.3 update
  src/components/real/cdh/c2a_communication.hpp
  src/components/real/cdh/on_board_computer_with_c2a.cpp
Labels: priority::high, C2A, patch

#726 Add Earth surface pointing mode for Controlled attitude
  settings/sample_satellite/satellite.ini
  src/dynamics/attitude/controlled_attitude.cpp
  src/dynamics/attitude/controlled_attitude.hpp
  src/dynamics/attitude/initialize_attitude.cpp
Labels: priority::high, dynamics, minor update
