Repository ut-issl/s2e-core, pull requests merged in 2024-08, with the labels that each got.

#661 Move logs directory
  .gitignore
  data/sample/initialize_files/sample_simulation_base.ini
  logs/.gitkeep
  scripts/Plot/common.py
Labels: priority::medium, tools, automation::comment-graph, gui, major update

#662 Move initialize_files directory
  .github/workflows/build.yml
  CMakeLists.txt
  data/sample/initialize_files/components/wings_command_sender_to_c2a/wings_command_sender_to_c2a.ini
  settings/components/angular_velocity_observer.ini
  settings/components/antenna_radiation_pattern_csv_files/sample_antenna_radiation_pattern.csv
  settings/components/attitude_observer.ini
  settings/components/battery.ini
  settings/components/component_interference.ini
  settings/components/force_generator.ini
  settings/components/gnss_receiver.ini
  settings/components/ground_station_antenna.ini
  settings/components/ground_station_calculator.ini
  settings/components/gyro_sensor.ini
  settings/components/magnetometer.ini
  settings/components/magnetorquer.ini
  settings/components/orbit_observer.ini
  settings/components/pcu_initial_study.ini
  settings/components/reaction_wheel.ini
  settings/components/rw_disturbance_csv_files/radial_force_harmonics_coefficients.csv
  settings/components/rw_disturbance_csv_files/radial_torque_harmonics_coefficients.csv
  settings/components/solar_array_panel.ini
  settings/components/spacecraft_antenna.ini
  settings/components/star_sensor.ini
  settings/components/sun_sensor.ini
  settings/components/telescope.ini
  settings/components/thermal_components.ini
  settings/components/thruster.ini
  settings/components/torque_generator.ini
  settings/components/wings_command_sender_to_c2a/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  settings/components/wings_command_sender_to_c2a/example.ops
  settings/components/wings_command_sender_to_c2a/wings_command_sender_to_c2a.ini
  settings/gnss/final_products/.gitkeep
  settings/sample_disturbance.ini
  settings/sample_gnss.ini
  settings/sample_ground_station.ini
  settings/sample_inter_satellite_communication.ini
  settings/sample_local_environment.ini
  settings/sample_satellite.ini
  settings/sample_simulation_base.ini
  settings/sample_structure.ini
  settings/thermal_csv_files/cij.csv
  settings/thermal_csv_files/heaters.csv
  settings/thermal_csv_files/heatload.csv
  settings/thermal_csv_files/node.csv
  settings/thermal_csv_files/rij.csv
Labels: priority::medium, major update

#663 Feature/refactor settings
  scripts/Plot/plot_gs_visibility.py
  settings/components/wings_command_sender_to_c2a/wings_command_sender_to_c2a.ini
  settings/environment/gnss/final_products/.gitkeep
  settings/environment/sample_gnss.ini
  settings/sample_ground_station.ini
  settings/sample_ground_station/components/antenna_radiation_pattern_csv_files/sample_antenna_radiation_pattern.csv
  settings/sample_ground_station/components/ground_station_antenna.ini
  settings/sample_ground_station/components/ground_station_calculator.ini
  settings/sample_ground_station/ground_station.ini
  settings/sample_satellite/components/angular_velocity_observer.ini
  settings/sample_satellite/components/antenna_radiation_pattern_csv_files/sample_antenna_radiation_pattern.csv
  settings/sample_satellite/components/attitude_observer.ini
  settings/sample_satellite/components/battery.ini
  settings/sample_satellite/components/component_interference.ini
  settings/sample_satellite/components/force_generator.ini
  settings/sample_satellite/components/gnss_receiver.ini
  settings/sample_satellite/components/gyro_sensor.ini
  settings/sample_satellite/components/magnetometer.ini
  settings/sample_satellite/components/magnetorquer.ini
  settings/sample_satellite/components/orbit_observer.ini
  settings/sample_satellite/components/pcu_initial_study.ini
  settings/sample_satellite/components/reaction_wheel.ini
  settings/sample_satellite/components/rw_disturbance_csv_files/radial_force_harmonics_coefficients.csv
  settings/sample_satellite/components/rw_disturbance_csv_files/radial_torque_harmonics_coefficients.csv
  settings/sample_satellite/components/solar_array_panel.ini
  settings/sample_satellite/components/spacecraft_antenna.ini
  settings/sample_satellite/components/star_sensor.ini
  settings/sample_satellite/components/sun_sensor.ini
  settings/sample_satellite/components/telescope.ini
  settings/sample_satellite/components/thermal_components.ini
  settings/sample_satellite/components/thruster.ini
  settings/sample_satellite/components/torque_generator.ini
  settings/sample_satellite/components/wings_command_sender_to_c2a/SAMPLE_MOBC_CMD_DB_CMD_DB.csv
  settings/sample_satellite/components/wings_command_sender_to_c2a/example.ops
  settings/sample_satellite/components/wings_command_sender_to_c2a/wings_command_sender_to_c2a.ini
  settings/sample_satellite/disturbance.ini
  settings/sample_satellite/local_environment.ini
  settings/sample_satellite/satellite.ini
  settings/sample_satellite/structure.ini
  settings/sample_satellite/thermal_csv_files/cij.csv
  settings/sample_satellite/thermal_csv_files/heaters.csv
  settings/sample_satellite/thermal_csv_files/heatload.csv
  settings/sample_satellite/thermal_csv_files/node.csv
  settings/sample_satellite/thermal_csv_files/rij.csv
  settings/sample_simulation_base.ini
  src/s2e.cpp
Labels: priority::medium, major update

#660 Add new namespaces
  src/components/real/aocs/gnss_receiver.hpp
  src/components/real/aocs/reaction_wheel.hpp
  src/disturbances/geopotential.cpp
  src/disturbances/geopotential.hpp
  src/disturbances/lunar_gravity_field.cpp
  src/disturbances/lunar_gravity_field.hpp
  src/dynamics/orbit/orbit.hpp
  src/environment/global/moon_rotation.cpp
  src/environment/local/geomagnetic_field.cpp
  src/environment/local/geomagnetic_field.hpp
  src/math_physics/atmosphere/harris_priester_model.cpp
  src/math_physics/atmosphere/harris_priester_model.hpp
  src/math_physics/control_utilities/first_order_lag.hpp
  src/math_physics/geodesy/geodetic_position.cpp
  src/math_physics/geodesy/geodetic_position.hpp
  src/math_physics/gravity/gravity_potential.cpp
  src/math_physics/gravity/gravity_potential.hpp
  src/math_physics/gravity/test_gravity_potential.cpp
  src/math_physics/optics/gaussian_beam_base.cpp
  src/math_physics/optics/gaussian_beam_base.hpp
  src/math_physics/planet_rotation/moon_rotation_utilities.cpp
  src/math_physics/planet_rotation/moon_rotation_utilities.hpp
  src/simulation/ground_station/ground_station.cpp
  src/simulation/ground_station/ground_station.hpp
Labels: priority::medium, major update

#658 Add orbit namespace
  src/dynamics/orbit/encke_orbit_propagation.cpp
  src/dynamics/orbit/encke_orbit_propagation.hpp
  src/dynamics/orbit/initialize_orbit.cpp
  src/dynamics/orbit/kepler_orbit_propagation.hpp
  src/dynamics/orbit/relative_orbit.cpp
  src/dynamics/orbit/relative_orbit.hpp
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/math_physics/numerical_integration/test_runge_kutta.cpp
  src/math_physics/orbit/interpolation_orbit.cpp
  src/math_physics/orbit/interpolation_orbit.hpp
  src/math_physics/orbit/kepler_orbit.cpp
  src/math_physics/orbit/kepler_orbit.hpp
  src/math_physics/orbit/orbital_elements.cpp
  src/math_physics/orbit/orbital_elements.hpp
  src/math_physics/orbit/relative_orbit_models.cpp
  src/math_physics/orbit/relative_orbit_models.hpp
  src/math_physics/orbit/test_interpolation_orbit.cpp
Labels: priority::medium, major update

#657 Add gnss namespace
  src/dynamics/orbit/encke_orbit_propagation.cpp
  src/dynamics/orbit/encke_orbit_propagation.hpp
  src/dynamics/orbit/initialize_orbit.cpp
  src/dynamics/orbit/kepler_orbit_propagation.hpp
  src/dynamics/orbit/relative_orbit.cpp
  src/dynamics/orbit/relative_orbit.hpp
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/math_physics/gnss/antex_file_reader.cpp
  src/math_physics/gnss/antex_file_reader.hpp
  src/math_physics/gnss/bias_sinex_file_reader.cpp
  src/math_physics/gnss/bias_sinex_file_reader.hpp
  src/math_physics/gnss/gnss_satellite_number.cpp
  src/math_physics/gnss/gnss_satellite_number.hpp
  src/math_physics/gnss/igs_product_name_handling.hpp
  src/math_physics/gnss/sp3_file_reader.cpp
  src/math_physics/gnss/sp3_file_reader.hpp
  src/math_physics/gnss/test_antex_file_reader.cpp
  src/math_physics/gnss/test_bias_sinex_file_reader.cpp
  src/math_physics/gnss/test_gnss_satellite_number.cpp
  src/math_physics/gnss/test_igs_product_name_handling.cpp
  src/math_physics/gnss/test_sp3_file_reader.cpp
  src/math_physics/numerical_integration/test_runge_kutta.cpp
  src/math_physics/orbit/interpolation_orbit.cpp
  src/math_physics/orbit/interpolation_orbit.hpp
  src/math_physics/orbit/kepler_orbit.cpp
  src/math_physics/orbit/kepler_orbit.hpp
  src/math_physics/orbit/orbital_elements.cpp
  src/math_physics/orbit/orbital_elements.hpp
  src/math_physics/orbit/relative_orbit_models.cpp
  src/math_physics/orbit/relative_orbit_models.hpp
  src/math_physics/orbit/test_interpolation_orbit.cpp
Labels: priority::medium, major update

#659 Add `time_system` namespace
  src/components/real/aocs/gnss_receiver.hpp
  src/components/real/aocs/reaction_wheel.hpp
  src/disturbances/geopotential.cpp
  src/disturbances/geopotential.hpp
  src/disturbances/lunar_gravity_field.cpp
  src/disturbances/lunar_gravity_field.hpp
  src/dynamics/orbit/orbit.hpp
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/environment/global/moon_rotation.cpp
  src/environment/local/geomagnetic_field.cpp
  src/environment/local/geomagnetic_field.hpp
  src/math_physics/atmosphere/harris_priester_model.cpp
  src/math_physics/atmosphere/harris_priester_model.hpp
  src/math_physics/control_utilities/first_order_lag.hpp
  src/math_physics/geodesy/geodetic_position.cpp
  src/math_physics/geodesy/geodetic_position.hpp
  src/math_physics/gnss/antex_file_reader.cpp
  src/math_physics/gnss/antex_file_reader.hpp
  src/math_physics/gnss/sp3_file_reader.cpp
  src/math_physics/gnss/sp3_file_reader.hpp
  src/math_physics/gravity/gravity_potential.cpp
  src/math_physics/gravity/gravity_potential.hpp
  src/math_physics/gravity/test_gravity_potential.cpp
  src/math_physics/optics/gaussian_beam_base.cpp
  src/math_physics/optics/gaussian_beam_base.hpp
  src/math_physics/planet_rotation/moon_rotation_utilities.cpp
  src/math_physics/planet_rotation/moon_rotation_utilities.hpp
  src/math_physics/time_system/date_time_format.cpp
  src/math_physics/time_system/date_time_format.hpp
  src/math_physics/time_system/epoch_time.cpp
  src/math_physics/time_system/epoch_time.hpp
  src/math_physics/time_system/gps_time.cpp
  src/math_physics/time_system/gps_time.hpp
  src/math_physics/time_system/test_date_time_format.cpp
  src/math_physics/time_system/test_epoch_time.cpp
  src/math_physics/time_system/test_gps_time.cpp
  src/simulation/ground_station/ground_station.cpp
  src/simulation/ground_station/ground_station.hpp
Labels: priority::medium, major update

#670 [hotfix] Add const getter of PowerPort in PowerControlUnit
  src/components/real/power/power_control_unit.hpp
Labels: priority::medium, patch

#673 [Hotfix] Fix typo in comment
  src/components/real/cdh/on_board_computer_with_c2a.hpp
Labels: bug, documentation, patch

#672 [Hotfix] Update patch version to v7.2.8
  CMakeLists.txt
Labels: priority::low, patch

#671 Merge main into develop for hotfix #670
  CMakeLists.txt
  src/components/real/cdh/on_board_computer_with_c2a.hpp
  src/components/real/power/power_control_unit.hpp
Labels: priority::low, patch

#618 Refactor logger class impl with std::filesystem
  src/logger/logger.cpp
  src/logger/logger.hpp
Labels: priority::medium, automation::comment-graph, library, minor update

#630 Split C2A communication functions prototype declaration header
  src/components/real/cdh/c2a_communication.hpp
  src/components/real/cdh/on_board_computer_with_c2a.hpp
Labels: priority::medium, C2A, minor update

#674 [Hotfix] Fix missing value in comment
  src/components/real/power/solar_array_panel.hpp
Labels: priority::low, patch

#675 Merge main into develop for hotfix #674
  src/components/real/power/solar_array_panel.hpp
Labels: priority::low, patch

#677 Add magnetic field setting file
  settings/environment/magnetic_field/igrf11.coef
  settings/environment/magnetic_field/igrf12.coef
  settings/environment/magnetic_field/igrf13.coef
  settings/sample_satellite/local_environment.ini
Labels: priority::medium, major update

#678 Add space weather directory
  .github/workflows/build.yml
  .github/workflows/google-test.yml
  ExtLibraries/nrlmsise00/CMakeLists.txt
  settings/environment/space_weather/.gitkeep
  settings/sample_satellite/local_environment.ini
Labels: priority::medium, major update

#679 Add CSPICE settings
  ExtLibraries/cspice/CMakeLists.txt
  settings/environment/cspice/.gitkeep
  settings/sample_simulation_base.ini
Labels: priority::medium, major update

#680 Add star_catalogue settings
  scripts/Common/download_HIPcatalogue.sh
  settings/environment/star_catalogue/.gitkeep
  settings/sample_simulation_base.ini
Labels: priority::medium, major update

#681 Add ignore for new setting files
  .gitignore
Labels: priority::medium, minor update

#682 Rename INI_FILE_DIR_FROM_EXE to SETTINGS_DIR_FROM_EXE
  .github/workflows/build.yml
  CMakeLists.txt
  common.cmake
  settings/environment/sample_gnss.ini
  settings/sample_ground_station/components/ground_station_antenna.ini
  settings/sample_ground_station/ground_station.ini
  settings/sample_satellite/components/reaction_wheel.ini
  settings/sample_satellite/components/spacecraft_antenna.ini
  settings/sample_satellite/components/wings_command_sender_to_c2a/wings_command_sender_to_c2a.ini
  settings/sample_satellite/disturbance.ini
  settings/sample_satellite/local_environment.ini
  settings/sample_satellite/satellite.ini
  settings/sample_simulation_base.ini
  src/s2e.cpp
  src/setting_file_reader/initialize_file_access.cpp
Labels: priority::medium, minor update

#685 Fix ini file copy for telescope
  src/simulation_sample/spacecraft/sample_components.cpp
Labels: priority::medium, minor update
