Repository ut-issl/s2e-core, pull requests merged in 2024-01, with the labels that each got.

#567 [Hotfix] Change default attitude initialize mode
  CMakeLists.txt
  data/sample/initialize_files/sample_satellite.ini
Labels: priority::high, patch

#568 Merge main to develop for Hotfix #567
  CMakeLists.txt
  data/sample/initialize_files/sample_satellite.ini
Labels: priority::high, patch

#558 Delete estimated GNSS position value
  data/sample/initialize_files/sample_gnss.ini
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/environment/global/initialize_gnss_satellites.cpp
Labels: priority::medium, environment, major update

#559 Replace index/satellite-number conversion functions in gnss satellites
  src/components/real/aocs/gnss_receiver.cpp
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/library/gnss/antex_file_reader.cpp
  src/library/gnss/gnss_satellite_number.cpp
  src/library/gnss/gnss_satellite_number.hpp
  src/library/gnss/test_gnss_satellite_number.cpp
Labels: priority::medium, environment, minor update

#560 Fix GNSS function and variable name
  src/components/real/aocs/gnss_receiver.cpp
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
Labels: priority::medium, environment, minor update

#571 [hotfix] fix force_generator
  src/components/ideal/force_generator.cpp
Labels: bug, component, patch, major update

#572 [Hotfix] Fix torque generator
  CMakeLists.txt
  src/components/ideal/torque_generator.cpp
  src/simulation_sample/spacecraft/sample_components.cpp
Labels: bug, priority::high, component, patch

#573 Merge main to develop for HOTFIX #571 and #572
  CMakeLists.txt
  src/components/ideal/force_generator.cpp
  src/components/ideal/torque_generator.cpp
  src/simulation_sample/spacecraft/sample_components.cpp
Labels: priority::high, patch

#577 [Hotfix] Remove enhanced comment and preceding whitespace from str…
  CMakeLists.txt
  src/library/initialize/initialize_file_access.cpp
Labels: priority::high, patch

#578 Merge main to develop for HOTFIX #577
  CMakeLists.txt
  src/library/initialize/initialize_file_access.cpp
Labels: priority::high, patch

#586 Fix version of numpy-quaternion
  scripts/Plot/Pipfile
  scripts/Plot/Pipfile.lock
Labels: priority::medium, automation::comment-graph, gui, minor update

#581 Remove unnecessary enums in GNSS
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
  src/environment/global/initialize_gnss_satellites.cpp
Labels: priority::medium, environment, major update

#582 Simplify GnssSatellite class
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
Labels: priority::medium, environment, major update

#583 Remove unused header includes
  src/environment/global/gnss_satellites.cpp
  src/environment/global/gnss_satellites.hpp
Labels: priority::medium, environment, patch
