Repository ut-issl/s2e-core, pull requests merged in 2024-03, with the labels that each got.

#604 Add ECEF position log
  scripts/Plot/plot_gnss_receiver.py
  src/dynamics/orbit/orbit.cpp
Labels: priority::medium, gui, dynamics, minor update

#595 Add orbit observer
  data/sample/initialize_files/components/orbit_observer.ini
  data/sample/initialize_files/sample_satellite.ini
  scripts/Plot/plot_orbit_observer.py
  src/components/CMakeLists.txt
  src/components/ideal/orbit_observer.cpp
  src/components/ideal/orbit_observer.hpp
  src/simulation_sample/spacecraft/sample_components.cpp
  src/simulation_sample/spacecraft/sample_components.hpp
Labels: priority::medium, component, minor update

#619 Make C2A command sender optional
  CMakeLists.txt
  src/components/CMakeLists.txt
Labels: priority::medium, tools, C2A, patch

#626 Patch update v7.2.5
  CMakeLists.txt
Labels: priority::high, patch

#627 Merge main to develop for v7.2.5 patch update
  CMakeLists.txt
  src/components/CMakeLists.txt
Labels: priority::high, patch

#597 Fix GNSS receiver ini file
  data/sample/initialize_files/components/gnss_receiver.ini
  src/components/real/aocs/gnss_receiver.cpp
  src/components/real/aocs/gnss_receiver.hpp
Labels: priority::medium, component, major update

#601 Modify GNSS visibility calculation
  data/sample/initialize_files/components/gnss_receiver.ini
  src/components/real/aocs/gnss_receiver.cpp
  src/components/real/aocs/gnss_receiver.hpp
  src/environment/global/gnss_satellites.hpp
Labels: priority::medium, component, major update

#602 Final check for GnssReceiver refactoring
  scripts/Plot/plot_gnss_receiver.py
  src/components/real/aocs/gnss_receiver.cpp
  src/dynamics/orbit/orbit.cpp
Labels: priority::medium, component, major update

#628 Fix C2A command sender source file path
  src/components/CMakeLists.txt
Labels: bug

#617 Add Relative Velocity Direction Pointing
  data/sample/initialize_files/sample_satellite.ini
  src/dynamics/attitude/controlled_attitude.cpp
  src/dynamics/attitude/controlled_attitude.hpp
Labels: priority::medium, dynamics, minor update

#635 Fix include path for orbit observer
  src/components/ideal/orbit_observer.cpp
  src/components/ideal/orbit_observer.hpp
Labels: priority::high, library, minor update

#632 Merge main to develop for v7.2.6 patch update
  CMakeLists.txt
  src/components/CMakeLists.txt
Labels: priority::high, patch
