Repository ut-issl/s2e-core, pull requests merged in 2025-02, with the labels that each got.

#739 Add effect of radio wave propagation time to geometric distance calculation
  settings/sample_satellite/components/gnss_receiver.ini
  src/components/real/aocs/gnss_receiver.cpp
  src/components/real/aocs/gnss_receiver.hpp
  src/environment/global/simulation_time.cpp
  src/environment/global/simulation_time.hpp
  src/math_physics/time_system/epoch_time.cpp
  src/math_physics/time_system/epoch_time.hpp
Labels: priority::medium, component, major update

#742 Mitigating Spherical Harmonic Singularities in IGRF Calculations
  src/math_physics/geomagnetic/igrf.cpp
Labels: bug, environment

#743 Main to Develop merge for v8.0.4 update
  src/math_physics/geomagnetic/igrf.cpp
Labels: environment, patch
